// Consolidation C1, Part 1: the ONE schema-validation service. Everything
// that checks names or structure against a standard's real schema lives
// here -- before this round it was spread over five modules, each with its
// own extraction and messages:
//   utils/vocabularyCheck.js   BRDP text (Title/Definition/Proposal)
//   utils/ruleNameCheck.js     rule XPath expressions (objectPath, @context, @test)
//   utils/answerNameCheck.js   Ask answers
//   utils/ruleTestSkeleton.js  structure of the Test rule examples
//   utils/ruleXPathSyntax.js   XPath syntax of a rule
// The code below is the same code, moved without changing its behavior
// (every existing test passes unchanged; only import paths moved). Pure and
// framework-free, importable from plain Node like src/prompts/.
//
// Sections:
//   1. Vocabulary loading
//   2. Name extraction by source: free text, XPath expressions, Ask answers,
//      XML documents (the Test rule examples)
//   3. Contrast with the vocabulary (not found / wrong type)
//   4. Structure (child allowed in its parent, attribute on its element)
//   5. XPath syntax (fontoxpath, syntax errors only)
//   5b. Rule format: what is saved as a rule contains a rule of the format
//   6. Messages: every finding as { source, code, params }, one i18n key
//      table and one formatter -- the texts each panel showed before.
import fontoxpath from 'fontoxpath';
import { wrapRuleXmlFragment } from '../utils/ruleXmlFragment.js';

// ═══ 1-3. BRDP text: vocabulary, free-text extraction, contrast ════════════

// Docs request (Suggest Proposal round, "comprobación de vocabulario contra
// el esquema"): checks element/attribute names mentioned in a BRDP's
// Title/Definition/Proposal against the REAL schema vocabulary of the
// project's standard, generated by backend/scripts/generate_schema_
// vocabulary.py from the actual XSDs (never guessed, never LLM-judged --
// see checkAgainstVocabulary below).
//
// Real-Mistral follow-up round ("solo determinista, sin bloqueo, sin
// referencias inventadas"): the LLM-guess extraction path was removed
// entirely -- only the deterministic path below remains, which requires
// actual evidence in the text (`<x>`/`@x` markup, or a name explicitly
// introduced via "element .../attribute ...") before ever calling a name
// a candidate at all.
//
// Follow-up round ("consejo de nombres sin falsos positivos"): a real
// report against this app -- "Atributos seleccionados para la etiqueta
// <stranger>" -> "Did you mean `@seleccionados`?"; "Decidir qué atributos
// usar en el elemento <stranger> y cómo usarlos." -> "Did you mean
// `@usar`?" and "Did you mean `<c>`?" -- exposed two real bugs, both fixed
// below, never with an LLM:
//   (a) a phrase-triggered bare word ("seleccionados", "usar") was
//       reported as a vocabulary WARNING (notFound) purely because it sat
//       right after "atributo(s)"/"elemento(s)", even though in Spanish
//       (and English) that word is very often an adjective or verb, not a
//       name -- e.g. "atributos SELECCIONADOS", "atributos a USAR". Fixed
//       by no longer letting a phrase-triggered candidate contribute to
//       notFound/wrongType AT ALL -- it is used ONLY to offer a "Did you
//       mean" suggestion, and only when the word actually resolves
//       against the real vocabulary (see resolvePhraseCandidates below).
//       A word that isn't in the vocabulary either way is silently
//       ignored -- no warning, no suggestion (accepted limitation: "el
//       elemento pokemon" -- a genuinely invented name -- gets nothing).
//   (b) the tokenizer only matched ASCII letters ([A-Za-z]), so an
//       accented word like "cómo" split into fragments ("c" + "mo") at
//       the accented character -- and because the list-continuation
//       feature (a previous round) treats "y"/"and"/etc. as continuing a
//       trigger's candidate list, the single-letter fragment "c" (from
//       "...elemento <stranger> y cómo...") got chained onto the
//       "elemento" trigger's list as if it were a second candidate,
//       producing the nonsensical "Did you mean `<c>`?". Fixed with a
//       Unicode-aware tokenizer (`\p{L}` letters, digits, and the XML
//       name characters -, _, .) so accented/composed words are always
//       captured whole -- never fragmented -- combined with (a) above
//       (even a whole, correctly-tokenized "cómo" would still resolve to
//       nothing and be ignored, since it isn't in any real schema).
export const STANDARD_TO_VOCABULARY_FILE = {
  'DITA 1.3 Xpath2.0': 'schema-vocabulary-dita.json',
  'DITA 1.3 Xpath3.0': 'schema-vocabulary-dita.json',
  'S1000D 3.0.1': 'schema-vocabulary-3-0-1.json',
  'S1000D 4.1': 'schema-vocabulary-4-1.json',
  'S1000D 4.2': 'schema-vocabulary-4-2.json',
};

const _vocabularyCache = new Map();

// Returns { elements: Set<string>, attributes: Set<string> } for a standard
// with a generated vocabulary, or null if the standard has none (HR7 --
// the caller must show "not available", never silently skip or, worse,
// silently claim every name is fine).
export async function loadSchemaVocabulary(standard) {
  const file = STANDARD_TO_VOCABULARY_FILE[standard];
  if (!file) return null;
  return loadVocabularyFile(file);
}

async function loadVocabularyFile(file) {
  if (_vocabularyCache.has(file)) return _vocabularyCache.get(file);
  const res = await fetch(`/${file}?v=` + Date.now());
  if (!res.ok) throw new Error(`Could not load ${file}`);
  const json = await res.json();
  const parsed = { elements: new Set(json.elements || []), attributes: new Set(json.attributes || []) };
  _vocabularyCache.set(file, parsed);
  return parsed;
}

// "Sugerencias para erratas y nombres de otro estándar", Part 2: the
// vocabularies of the OTHER standards, one per file (the two DITA flavors
// share one vocabulary, so they are one "DITA 1.3" entry), in this order.
// Loaded only when a marked name does not exist in the project's own
// standard (useNameFixHints), never when the page opens.
export const VOCABULARY_FILE_LABELS = [
  ['schema-vocabulary-3-0-1.json', 'S1000D 3.0.1'],
  ['schema-vocabulary-4-1.json', 'S1000D 4.1'],
  ['schema-vocabulary-4-2.json', 'S1000D 4.2'],
  ['schema-vocabulary-dita.json', 'DITA 1.3'],
];

// The label of the project's standard in the other-standard message
// ("DITA 1.3" for both DITA flavors, the standard itself otherwise).
export function vocabularyLabel(standard) {
  const file = STANDARD_TO_VOCABULARY_FILE[standard];
  const entry = VOCABULARY_FILE_LABELS.find(([f]) => f === file);
  return entry ? entry[1] : standard;
}

// [{ label, vocabulary }] for every vocabulary file except the project's.
// A file that cannot be loaded is left out (its standard just never
// appears in the message); the plain "not found" still shows.
export async function loadOtherStandardVocabularies(standard) {
  const own = STANDARD_TO_VOCABULARY_FILE[standard];
  const entries = await Promise.all(
    VOCABULARY_FILE_LABELS.filter(([file]) => file !== own).map(async ([file, label]) => {
      try {
        return { label, vocabulary: await loadVocabularyFile(file) };
      } catch (err) {
        console.error(`Could not load ${file}`, err);
        return null;
      }
    })
  );
  return entries.filter(Boolean);
}

// Deterministic context extraction -- the ONLY extraction path.
// - `elements`: whatever appears between `<...>` (opening or closing tag
//   form), e.g. `<pokemon>`/`</pokemon>` -> "pokemon".
// - `attributes`: whatever appears after `@`, e.g. `@conref` -> "conref".
// - `camelCase`: lower-camelCase words (e.g. "proceduralStep") -- checked
//   against the UNION of elements+attributes by checkAgainstVocabulary,
//   exactly like explicit markup, with its own "Not found" warning.
// - `phraseCandidates`: words introduced via "elemento(s)/element(s)/
//   atributo(s)/attribute(s)/etiqueta(s)/tag(s)" (see extractPhraseCandidates)
//   -- NEVER checked for notFound/wrongType (follow-up round: too often an
//   adjective or verb, not a name). Only used by resolvePhraseCandidates
//   to build a "Did you mean" suggestion, and only for names that
//   genuinely exist in the real vocabulary. Excludes any name already
//   properly marked up elsewhere in the same text (already present in
//   `elements`/`attributes`).
export function extractContextCandidates(text) {
  const source = text || '';
  const elements = new Set();
  const attributes = new Set();

  let match;
  ELEMENT_ATTR_TAG_RE.lastIndex = 0;
  while ((match = ELEMENT_ATTR_TAG_RE.exec(source))) elements.add(match[1]);

  ATTR_MARKER_RE.lastIndex = 0;
  while ((match = ATTR_MARKER_RE.exec(source))) attributes.add(match[1]);

  // "Did you mean con marcado a medias" round, Part 1: a half-typed tag
  // ("Title above the <table", "above the table>") is just as explicit an
  // intent to mark up an element as a complete `<table>` -- the missing
  // bracket is a typo, not ambiguity about whether the author meant to
  // mark it up at all. So these names are folded into the SAME `elements`
  // Set that checkAgainstVocabulary reads -- UNLIKE phraseCandidates below
  // (which never produce a warning, only a suggestion): a dangling name
  // that doesn't exist in the schema gets the same red "not found" banner
  // a complete `<pokemon>` would, per the encargo ("porque la intención de
  // marcar es explícita"). A name already captured via a complete tag
  // elsewhere in the same text is never duplicated. `danglingElements`
  // (returned separately below) is ONLY the subset of names that were
  // genuinely incomplete -- used later to also offer a "Did you mean
  // <name>?" completion when the name resolves (resolveDanglingElement
  // Suggestions), the same way a phrase-triggered word does.
  const danglingElements = [];
  for (const name of extractDanglingElementNames(source)) {
    if (elements.has(name)) continue;
    elements.add(name);
    danglingElements.push(name);
  }

  const camelCase = extractCamelCaseCandidates(source);

  const rawPhraseCandidates = extractPhraseCandidates(source);
  const phraseCandidates = [];
  const seenPhrase = new Set();
  for (const c of rawPhraseCandidates) {
    if (elements.has(c.name) || attributes.has(c.name)) continue; // already marked up somewhere in this text
    const key = `${c.type}:${c.name}`;
    if (seenPhrase.has(key)) continue;
    seenPhrase.add(key);
    phraseCandidates.push({ name: c.name, type: c.type });
  }

  return { elements: [...elements], attributes: [...attributes], camelCase, phraseCandidates, danglingElements };
}

// "Falsos avisos del marcado a medias" round: the previous version only
// ever looked at ONE side of the bracket (the character right after "<",
// or right before ">") -- it never checked the OTHER side, so a plain
// comparison/arrow whose captured "name" happened to sit flush against a
// letter/digit on that other side was wrongly treated as dangling markup.
// Real false positives reported, all now confirmed fixed: "if count>5
// then" -> "<count>", "value>limit" -> "<value>", "A->B" -> "<A->", "x<y"
// -> "<y>", "Steps 1<n<3" -> "<n>", "a<b and c>d" -> "<b>"/"<c>",
// "temperatura<máxima" -> "<máxima>".
//
// Fixed with two independent rules, BOTH required:
//   1. The captured name may never END in "-" or "_" -- this alone kills
//      "A->B": the old permissive [\p{L}\p{N}_-]* class let the regex
//      greedily capture "A-" as the "name" right before the literal ">".
//      The new name pattern only allows a run of [\p{L}\p{N}_-] when it
//      ends in an actual letter/digit (or is a single bare letter).
//   2. BOTH sides of the bracket must be a genuine word boundary --
//      start/end of text, or anything that is not a letter, not a digit,
//      and (where markup could otherwise directly abut the candidate)
//      not "<"/">" either:
//        - "<name": the character right before "<" must not be a
//          letter/digit (kills "x<y", "1<n", "a<b" -- in each, the
//          character immediately before "<" is itself a letter/digit),
//          and the character right after the name must not be a
//          letter/digit/"<"/">" (excludes an immediately-following tag
//          and, together with rule 1, a fully-closed "<table>").
//        - "name>": the character right before the name must not be a
//          letter/digit/"<"/">" (the "<"/">" exclusion is what keeps an
//          already-complete "<table>" from being reported a second time
//          as a dangling close -- unchanged from before this round), and
//          the character right after ">" must not be a letter/digit
//          (kills "count>5", "value>limit", "c>d" -- in each, the
//          character immediately after ">" is itself a letter/digit).
// Genuinely good cases are unaffected: "encima de la <table" (space
// before "<", end-of-text after "table"), "la table> va" (space before
// "table", space after ">"), "<para>text</para>" (already-complete tags,
// deduped against `elements` before ever reaching `danglingElements`).
function isLetterOrDigit(ch) {
  return ch !== undefined && /[\p{L}\p{N}]/u.test(ch);
}

function extractDanglingElementNames(text) {
  const source = text || '';
  const names = new Set();

  OPEN_TOKEN_RE.lastIndex = 0;
  let m;
  while ((m = OPEN_TOKEN_RE.exec(source))) {
    const before = m.index > 0 ? source[m.index - 1] : undefined;
    if (isLetterOrDigit(before)) continue; // e.g. "x<y", "1<n", "a<b"
    const endIdx = m.index + m[0].length;
    const after = source[endIdx];
    if (isLetterOrDigit(after) || after === '<' || after === '>') continue; // e.g. "<table>", "<table<"
    names.add(m[1]);
  }

  CLOSE_TOKEN_RE.lastIndex = 0;
  while ((m = CLOSE_TOKEN_RE.exec(source))) {
    const before = m.index > 0 ? source[m.index - 1] : undefined;
    if (isLetterOrDigit(before) || before === '<' || before === '>') continue; // e.g. "<table>" (complete)
    const endIdx = m.index + m[0].length;
    const after = source[endIdx];
    if (isLetterOrDigit(after)) continue; // e.g. "count>5", "value>limit", "c>d"
    names.add(m[1]);
  }

  return [...names];
}

// Follow-up round ("sin falsos positivos"): the ONLY place a phrase-
// triggered candidate can turn into anything user-visible -- a "Did you
// mean" suggestion, NEVER a warning. A candidate resolves only if it
// genuinely exists in the vocabulary, as EITHER kind:
//   - exists as the kind the trigger implied ("atributo table" where
//     `table` is a real attribute) -> suggested as that kind;
//   - exists only as the OTHER kind ("atributo table" where `table` is
//     really an element) -> suggested with the CORRECTED kind
//     (`<table>`, never `@table`);
//   - exists as neither -> dropped entirely, no suggestion, no warning
//     (accepted limitation: a genuinely invented name like "pokemon"
//     never gets a suggestion).
// `vocabulary` may be null (standard with no generated vocabulary) -- in
// that case nothing can be resolved, so this returns [] rather than
// guessing.
export function resolvePhraseCandidates(phraseCandidates, vocabulary) {
  if (!vocabulary) return [];
  const seen = new Set();
  const resolved = [];
  for (const c of phraseCandidates) {
    if (seen.has(c.name)) continue;
    const vocabSet = c.type === 'element' ? vocabulary.elements : vocabulary.attributes;
    const otherSet = c.type === 'element' ? vocabulary.attributes : vocabulary.elements;
    let type;
    if (vocabSet.has(c.name)) type = c.type;
    else if (otherSet.has(c.name)) type = c.type === 'element' ? 'attribute' : 'element';
    else continue; // doesn't exist as either kind -- ignored entirely
    seen.add(c.name);
    resolved.push({ name: c.name, type });
  }
  return resolved;
}

// "Did you mean con marcado a medias" round, Part 1: half-typed markup
// (`danglingElements` from extractContextCandidates) only ever suggests
// COMPLETING the bracket as an element -- unlike resolvePhraseCandidates
// above, it never flips to `@name`. The author already chose "<"/">" as
// the delimiter; the fix is to close it, never to change what kind of
// markup it is. A name that doesn't exist as an element in the vocabulary
// is never suggested here -- it already gets its own red "not found" (or
// wrongType, if it exists only as an attribute) warning from
// checkAgainstVocabulary, since extractContextCandidates folds these
// names into the same `elements` Set that check reads.
export function resolveDanglingElementSuggestions(danglingElementNames, vocabulary) {
  if (!vocabulary) return [];
  const seen = new Set();
  const resolved = [];
  for (const name of danglingElementNames) {
    if (seen.has(name)) continue;
    if (!vocabulary.elements.has(name)) continue;
    seen.add(name);
    resolved.push({ name, type: 'element' });
  }
  return resolved;
}

// Rewrites `text` to wrap the first bare (not already `<...>`/`@...`-marked)
// occurrence of `suggestion.name` with the markup its `type` implies --
// the "Did you mean `<pokemon>`?" fix-it action. Word-boundary match, case
// as written by the user (never re-cased). A no-op (returns `text`
// unchanged) if the name can no longer be found bare -- the caller re-runs
// extractContextCandidates after applying anyway, so a suggestion that's
// gone stale simply stops appearing rather than throwing.
//
// Ask-with-schema-cards follow-up round: a real report against this app --
// title "Element <table" (an unclosed "<" immediately before the name) --
// showed the button doing NOTHING. Root cause: the previous single regex
// `(?<![<@\w])name(?!\w)` treats ANY "<" right before the name as "already
// marked up" and refuses to match there at all -- for "Element <table"
// "table" only occurs once, immediately after that dangling "<", so the
// whole regex found zero matches anywhere and returned the input
// unchanged. The mirrored case ("table>", a dangling trailing ">" with no
// opening "<") used to match as a bare word and get wrapped AGAIN,
// producing a doubled bracket ("<table>>"). Both are now handled as their
// own cases, tried in order from most to least specific, so incomplete
// markup is completed (never doubled) and a genuinely bare word is wrapped
// normally:
//   1. `<name>` (already fully, correctly marked up) -- nothing to fix.
//   2. `<name` with no closing `>` right after -- add ONLY the missing
//      closing bracket, keep the existing opening one.
//   3. `name>` with no opening `<` right before -- add ONLY the missing
//      opening bracket, keep the existing closing one.
//   4. a genuinely bare occurrence -- wrap with both brackets.
// Attributes have no closing delimiter (`@name` is complete the moment the
// `@` is there), so they only ever need the bare-word case; a name already
// following `@` was already excluded upstream (extractContextCandidates
// never offers it as a phrase candidate to begin with).
export function applyRenameSuggestion(text, suggestion) {
  const source = text || '';
  const escaped = suggestion.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const bareRe = new RegExp(`(?<![<@\\w])${escaped}(?!\\w)`, 'u');

  if (suggestion.type === 'attribute') {
    const m = bareRe.exec(source);
    if (!m) return source;
    return source.slice(0, m.index) + `@${suggestion.name}` + source.slice(m.index + suggestion.name.length);
  }

  if (new RegExp(`<${escaped}>`, 'u').test(source)) return source; // already correct

  const danglingOpenRe = new RegExp(`<${escaped}(?!\\w)`, 'u'); // "<table", no ">" right after
  let m = danglingOpenRe.exec(source);
  if (m) return source.slice(0, m.index) + `<${suggestion.name}>` + source.slice(m.index + m[0].length);

  const danglingCloseRe = new RegExp(`(?<![<\\w])${escaped}>`, 'u'); // "table>", no "<" right before
  m = danglingCloseRe.exec(source);
  if (m) return source.slice(0, m.index) + `<${suggestion.name}>` + source.slice(m.index + m[0].length);

  m = bareRe.exec(source);
  if (!m) return source;
  return source.slice(0, m.index) + `<${suggestion.name}>` + source.slice(m.index + suggestion.name.length);
}

const ELEMENT_ATTR_TAG_RE = /<\/?([A-Za-z][\w-]*)[^>]*>/g;
const ATTR_MARKER_RE = /@([A-Za-z][\w-]*)/g;
// "Did you mean con marcado a medias" round, Part 1 (used only by
// extractDanglingElementNames above): `<`/`>` must be immediately (no
// space) adjacent to the name -- this is what excludes "a < b"/"x < y" as
// candidates, not any check against the vocabulary.
// "Falsos avisos del marcado a medias" round: the name's own character
// class no longer allows it to end in "-"/"_" -- a trailing run of either
// is only ever a real name if followed by a further letter/digit before
// the closing delimiter (single bare letters, e.g. "<n", still match on
// their own). This alone is what keeps "A->B" (old behavior: captured
// "A-" as the name right before the literal ">") from matching at all;
// the boundary checks in extractDanglingElementNames handle the rest.
const OPEN_TOKEN_RE = /<([\p{L}](?:[\p{L}\p{N}_-]*[\p{L}\p{N}])?)/gu;
const CLOSE_TOKEN_RE = /([\p{L}](?:[\p{L}\p{N}_-]*[\p{L}\p{N}])?)>/gu;
// Unicode-aware word tokenizer (follow-up round, point 3): letters in any
// script (`\p{L}`), digits, and the XML name characters -, _, . -- so an
// accented/composed word like "cómo"/"señal"/"utilizará" is always
// captured as ONE token, never fragmented at the accented character (the
// old ASCII-only [A-Za-z][\w-]* pattern broke "cómo" into "c" + "mo",
// which the list-continuation feature below could then chain onto a
// trigger's candidate list as a spurious single-letter "name").
const WORD_RE = /[\p{L}][\p{L}\p{N}_.-]*|,/gu;
const CAMEL_CASE_TOKEN_RE = /[\p{L}][\p{L}\p{N}_.-]*/gu;
// Follow-up round, point 2: requires at least two lowercase letters before
// the first uppercase one, AND a minimum total length of 5 -- "lA" (1
// lowercase, then uppercase) no longer matches; "dmCode"/"dmRef"/
// "proceduralStep"/"applicRefId" still do. The camelCase pattern itself
// stays ASCII (a-z/A-Z) -- real camelCase identifiers in this app's
// schemas are always ASCII; the Unicode-aware tokenizer above only
// matters for not FRAGMENTING a word before this pattern is tested
// against it.
const CAMEL_CASE_RE = /^[a-z]{2,}[A-Z][A-Za-z0-9]*$/;
const CAMEL_CASE_MIN_LENGTH = 5;

// Follow-up round, point 4: "etiqueta(s)"/"tag(s)" are real synonyms for
// "elemento(s)"/"element(s)" that a real user actually typed ("la
// etiqueta <stranger>") -- added as element-type triggers, same
// mechanism as the existing ones (the type-detection below only special-
// cases the attribute-type spellings, so these fall through to 'element'
// automatically, same as "elemento"/"element" already did).
const TRIGGER_WORDS = new Set([
  'elemento', 'elementos', 'element', 'elements',
  'etiqueta', 'etiquetas', 'tag', 'tags',
  'atributo', 'atributos', 'attribute', 'attributes',
]);
// Words skipped between a trigger word and the real candidate -- the
// original connectors (articles/prepositions) PLUS, per the follow-up
// round, the descriptive words a real report showed leaking through as
// false-positive candidates ("atributo de tipo cl" must yield "cl", never
// "tipo").
const SKIP_WORDS = new Set([
  'el', 'la', 'los', 'las', 'del', 'de', 'un', 'una', 'unos', 'unas', 'the', 'of', 'a', 'an',
  'tipo', 'type', 'llamado', 'llamada', 'named', 'called', 'nombre', 'name',
]);
// Words that continue a list right after a just-captured candidate ("cl,
// pl ni ip" / "cl, pl and ip") -- only interpreted as continuators
// immediately after a candidate, never elsewhere in the sentence.
const LIST_CONTINUATION_WORDS = new Set(['y', 'o', 'ni', 'and', 'or']);

// Each word knows whether it is written as markup (`<x`, `</x`, `@x`, or
// followed by `>`), which ends a list (see extractPhraseCandidates).
function tokenize(text) {
  const out = [];
  let m;
  WORD_RE.lastIndex = 0;
  while ((m = WORD_RE.exec(text))) {
    if (m[0] === ',') {
      out.push({ type: 'comma' });
      continue;
    }
    const before = text[m.index - 1];
    const after = text[m.index + m[0].length];
    const marked = before === '<' || before === '@' || (before === '/' && text[m.index - 2] === '<') || after === '>';
    out.push({ type: 'word', value: m[0], marked });
  }
  return out;
}

// Skips over SKIP_WORDS starting at `idx`; stops (without consuming) at a
// trigger word, a comma, or anything else.
function skipSkipWords(tokens, idx) {
  let i = idx;
  while (i < tokens.length && tokens[i].type === 'word' && SKIP_WORDS.has(tokens[i].value.toLowerCase())) i++;
  return i;
}

// Phrase-trigger extraction with list capture: the word following
// "elemento(s)/element(s)/atributo(s)/attribute(s)/etiqueta(s)/tag(s)",
// skipping SKIP_WORDS between the trigger and the real candidate -- if a
// SECOND trigger word is hit while skipping, the scan re-anchors on that
// later trigger instead (e.g. "atributos del elemento pokemon" captures
// "pokemon", tied to "elemento"). Once the first candidate is found, the
// scan continues capturing a comma/conjunction-separated list ("cl, pl ni
// ip"), skipping SKIP_WORDS again between each list separator and its
// word, and stops at the first word that isn't a clean list continuation.
// Each returned candidate carries `type` ('element' | 'attribute') from
// the trigger word that started its list. These candidates are ONLY ever
// resolved into a suggestion (never a warning) -- see
// resolvePhraseCandidates above.
function extractPhraseCandidates(text) {
  const tokens = tokenize(text);
  const candidates = [];
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];
    if (t.type !== 'word' || !TRIGGER_WORDS.has(t.value.toLowerCase())) continue;
    const lower = t.value.toLowerCase();
    const type = lower.startsWith('atributo') || lower.startsWith('attribute') ? 'attribute' : 'element';

    let j = skipSkipWords(tokens, i + 1);
    if (j >= tokens.length || tokens[j].type !== 'word') continue;
    if (TRIGGER_WORDS.has(tokens[j].value.toLowerCase())) continue; // re-anchor: let the outer loop reach this trigger itself

    candidates.push({ name: tokens[j].value, type });
    let k = j + 1;
    let previousMarked = tokens[j].marked;
    // List continuation: comma or a list conjunction, then (skipping
    // SKIP_WORDS again) another word -- repeat until the pattern breaks.
    // "Sugerencias para erratas" round, Part 3: only after an UNMARKED
    // word. A marked name (`<copyright>`, `@x`) is the name the trigger
    // was about, so the list ends there -- "the element <copyright> and
    // source of copyright information" never captures "source".
    while (!previousMarked) {
      let k2 = k;
      let isContinuator = false;
      if (tokens[k2] && tokens[k2].type === 'comma') {
        k2++;
        isContinuator = true;
      } else if (tokens[k2] && tokens[k2].type === 'word' && LIST_CONTINUATION_WORDS.has(tokens[k2].value.toLowerCase())) {
        k2++;
        isContinuator = true;
      }
      if (!isContinuator) break;
      k2 = skipSkipWords(tokens, k2);
      if (k2 >= tokens.length || tokens[k2].type !== 'word' || TRIGGER_WORDS.has(tokens[k2].value.toLowerCase())) break;
      candidates.push({ name: tokens[k2].value, type });
      previousMarked = tokens[k2].marked;
      k = k2 + 1;
    }
    i = k - 1; // avoid rescanning consumed list words as fresh triggers
  }
  return candidates;
}

function extractCamelCaseCandidates(text) {
  const tokens = text.match(CAMEL_CASE_TOKEN_RE) || [];
  return tokens.filter((t) => t.length >= CAMEL_CASE_MIN_LENGTH && CAMEL_CASE_RE.test(t));
}

// The only step that decides existence, purely deterministically against
// the real vocabulary. `vocabulary` is what loadSchemaVocabulary() returns,
// or null if not available for this standard.
//
// Returns { available, notFound, wrongType }:
// - `notFound`: display strings (`<x>`/`@x`/bare) for names found via
//   explicit `<x>`/`@x` markup or camelCase -- the only two sources that
//   feed this (follow-up round: phrase-triggered bare words NEVER
//   contribute here any more, see extractContextCandidates/
//   resolvePhraseCandidates above).
// - `wrongType`: `{ name, usedAs, actualAs }` for a name used as one kind
//   (element/attribute) that doesn't exist as that kind but DOES exist as
//   the other -- reported instead of (never in addition to) notFound for
//   that name. Only applies to explicit markup (camelCase's kind is
//   genuinely unknown, so it is never wrong-kind-checked).
export function checkAgainstVocabulary(contextCandidates, vocabulary) {
  if (!vocabulary) return { available: false, notFound: [], wrongType: [], typedNotFound: [] };

  const notFound = new Map();
  const wrongType = new Map();
  const typedNotFound = new Map();

  const considerTyped = (name, type) => {
    const vocabSet = type === 'element' ? vocabulary.elements : vocabulary.attributes;
    const otherSet = type === 'element' ? vocabulary.attributes : vocabulary.elements;
    if (vocabSet.has(name)) return; // known as the kind it was used as -- fine
    if (otherSet.has(name)) {
      if (!wrongType.has(name)) {
        wrongType.set(name, { name, usedAs: type, actualAs: type === 'element' ? 'attribute' : 'element' });
      }
      return;
    }
    const display = type === 'element' ? `<${name}>` : `@${name}`;
    if (!notFound.has(name)) notFound.set(name, display);
    if (!typedNotFound.has(`${type}:${name}`)) typedNotFound.set(`${type}:${name}`, { name, type });
  };

  const considerCamelCase = (name) => {
    if (vocabulary.elements.has(name) || vocabulary.attributes.has(name)) return;
    if (!notFound.has(name)) notFound.set(name, name);
  };

  for (const name of contextCandidates.elements) considerTyped(name, 'element');
  for (const name of contextCandidates.attributes) considerTyped(name, 'attribute');
  for (const name of contextCandidates.camelCase) considerCamelCase(name);

  // A wrong-kind finding is its own, more specific message -- never also
  // listed as merely "not found" for the same name.
  for (const name of wrongType.keys()) notFound.delete(name);

  return {
    available: true,
    notFound: [...notFound.values()].sort(),
    wrongType: [...wrongType.values()].sort((a, b) => a.name.localeCompare(b.name)),
    // The marked names of notFound (`<x>`, `@x`, half-typed `<x`; never a
    // camelCase word) with their kind, for nameFixHints below.
    typedNotFound: [...typedNotFound.values()]
      .filter(({ name }) => !wrongType.has(name))
      // same order as notFound: by display (`<x>` before `@x`)
      .sort((a, b) => {
        const show = (n) => (n.type === 'element' ? `<${n.name}>` : `@${n.name}`);
        return show(a) < show(b) ? -1 : show(a) > show(b) ? 1 : 0;
      }),
  };
}

// ═══ 3b. Typos and names of another standard ══════════════════════════════
//
// "Sugerencias para erratas y nombres de otro estándar". Only for MARKED
// names that do not exist (checkAgainstVocabulary's typedNotFound: `<x>`,
// `@x`, a half-typed `<x`/`x>`; in a rule, every name of its XPath) -- never
// for a loose word of the text. No AI. For each name, in this order:
//   1. the same name with other capitals in the project's standard
//      (`@emphasistype` -> `@emphasisType`): only those are suggested --
//      it is the same name, a farther one would be noise;
//   2. the exact name in another standard (`<levelledPara>` in 3.0.1 ->
//      "exists in S1000D 4.1 and 4.2"): only says where the name comes
//      from, never proposes an equivalent. Checked BEFORE the near names
//      of step 3: a name that exists as written elsewhere was written on
//      purpose, and a neighbour by spelling would be the wrong fix
//      (`<para>` in DITA is S1000D, not a typo of `<param>`/`<part>`);
//   3. near names of the same kind in the project's standard: an edit
//      distance (case-insensitive, an adjacent transposition counts as one
//      edit -- "tabel" -> "table") of at most 2, at most 1 for names of up
//      to 5 letters, and 0 (capitals only) for names of 1-2 letters (a
//      single edit is half of such a name: `<ab>` -> `<sb>` is no
//      suggestion). At most 3, nearest first; when more than 3 tie at the
//      nearest distance, none (there is no telling which one was meant).
// otherVocabularies === null means "not loaded yet": then only step 1 is
// answered and `needsOtherVocabularies` says the caller has to load them.

const NAME_FIX_MAX = 3;

function maxNameDistance(name) {
  if (name.length <= 2) return 0;
  if (name.length <= 5) return 1;
  return 2;
}

// Optimal string alignment distance (Levenshtein + adjacent transposition),
// giving up as soon as it is over `limit`.
function editDistance(a, b, limit) {
  if (Math.abs(a.length - b.length) > limit) return limit + 1;
  let prev2 = null;
  let prev = Array.from({ length: b.length + 1 }, (_, j) => j);
  for (let i = 1; i <= a.length; i++) {
    const cur = [i];
    let rowMin = i;
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      let v = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + cost);
      if (prev2 && i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) v = Math.min(v, prev2[j - 2] + 1);
      cur.push(v);
      if (v < rowMin) rowMin = v;
    }
    if (rowMin > limit) return limit + 1;
    prev2 = prev;
    prev = cur;
  }
  return prev[b.length];
}

// The names of `vocabulary` (same kind) that differ from `name` only in
// capitals, and the near ones (step 3 above), each sorted.
export function similarSchemaNames(name, type, vocabulary) {
  if (!vocabulary) return { caseOnly: [], near: [] };
  const pool = type === 'attribute' ? vocabulary.attributes : vocabulary.elements;
  const lower = name.toLowerCase();
  const limit = maxNameDistance(name);
  const caseOnly = [];
  const ranked = [];
  for (const candidate of pool) {
    if (candidate === name) continue;
    const candidateLower = candidate.toLowerCase();
    if (candidateLower === lower) {
      caseOnly.push(candidate);
      continue;
    }
    if (limit === 0) continue;
    const d = editDistance(lower, candidateLower, limit);
    if (d <= limit) ranked.push({ candidate, d });
  }
  ranked.sort((a, b) => a.d - b.d || a.candidate.localeCompare(b.candidate));
  let near = [];
  if (ranked.length > 0) {
    const tiedAtNearest = ranked.filter((r) => r.d === ranked[0].d).length;
    if (tiedAtNearest <= NAME_FIX_MAX) near = ranked.slice(0, NAME_FIX_MAX).map((r) => r.candidate);
  }
  return { caseOnly: caseOnly.sort().slice(0, NAME_FIX_MAX), near };
}

// The labels of the other standards whose vocabulary has `name` as the
// same kind, exactly as written.
export function standardsWithName(name, type, otherVocabularies) {
  return (otherVocabularies || [])
    .filter(({ vocabulary }) => (type === 'attribute' ? vocabulary.attributes : vocabulary.elements).has(name))
    .map(({ label }) => label);
}

// { hints, needsOtherVocabularies }: one hint per name of `typedNotFound`
// that has something to say -- { name, type, similar: [names],
// otherStandards: [labels] }.
export function nameFixHints(typedNotFound, vocabulary, otherVocabularies) {
  const hints = [];
  let needsOtherVocabularies = false;
  for (const { name, type } of typedNotFound || []) {
    const { caseOnly, near } = similarSchemaNames(name, type, vocabulary);
    if (caseOnly.length > 0) {
      hints.push({ name, type, similar: caseOnly, otherStandards: [] });
      continue;
    }
    if (otherVocabularies === null || otherVocabularies === undefined) {
      needsOtherVocabularies = true;
      continue;
    }
    const otherStandards = standardsWithName(name, type, otherVocabularies);
    if (otherStandards.length > 0) hints.push({ name, type, similar: [], otherStandards });
    else if (near.length > 0) hints.push({ name, type, similar: near, otherStandards: [] });
  }
  return { hints, needsOtherVocabularies };
}

// The "Did you mean" chips of one text field: one per near/capitals name of
// a marked name that does not exist ({ from, name, type }, applied with
// renameMarkedName). An other-standard name never gets a chip.
export function nameFixSuggestions(text, vocabulary, otherVocabularies) {
  if (!vocabulary) return [];
  const checked = checkAgainstVocabulary(extractContextCandidates(text || ''), vocabulary);
  const out = [];
  for (const hint of nameFixHints(checked.typedNotFound, vocabulary, otherVocabularies).hints) {
    for (const name of hint.similar) out.push({ from: hint.name, name, type: hint.type });
  }
  return out;
}

// Whether a text has a marked name whose hint depends on the other
// standards' vocabularies -- the only case in which they get loaded.
export function textNeedsOtherVocabularies(text, vocabulary) {
  if (!vocabulary) return false;
  const checked = checkAgainstVocabulary(extractContextCandidates(text || ''), vocabulary);
  return nameFixHints(checked.typedNotFound, vocabulary, null).needsOtherVocabularies;
}

// Replaces every marked occurrence of `from` with `name`: `<from>`,
// `</from>`, `<from attr…>`, a half-typed `<from`/`from>` (`type`
// 'element'), or `@from` ('attribute'). Loose words are never touched.
export function renameMarkedName(text, from, name, type) {
  const source = text || '';
  const escaped = from.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const end = '(?![\\p{L}\\p{N}_.-])';
  if (type === 'attribute') return source.replace(new RegExp(`@${escaped}${end}`, 'gu'), `@${name}`);
  return source
    .replace(new RegExp(`(<\\/?)${escaped}${end}`, 'gu'), `$1${name}`)
    .replace(new RegExp(`(?<![<\\p{L}\\p{N}_.-])${escaped}>`, 'gu'), `${name}>`);
}

// Joins standard labels, the shared family said once: "S1000D 4.1 y 4.2",
// "S1000D 3.0.1, 4.1 y DITA 1.3". `and` is the translated conjunction.
export function formatStandardList(labels, and) {
  let family = null;
  const items = labels.map((label) => {
    const [head, ...rest] = label.split(' ');
    const item = head === family && rest.length > 0 ? rest.join(' ') : label;
    family = head;
    return item;
  });
  return joinList(items, and);
}

function joinList(items, word) {
  if (items.length <= 1) return items.join('');
  return `${items.slice(0, -1).join(', ')} ${word} ${items[items.length - 1]}`;
}

// Formats one wrongType entry into the exact sentence shape the encargo
// asks for. Exported so the UI and buildUnknownNamesBlock format it
// identically (never two independently-drifting copies).
export function formatWrongTypeMessage(standard, entry) {
  const usedDisplay = entry.usedAs === 'element' ? `<${entry.name}>` : `@${entry.name}`;
  const actualDisplay = entry.actualAs === 'element' ? `element <${entry.name}>` : `attribute @${entry.name}`;
  // Both "element" and "attribute" start with a vowel sound -- "an" either way.
  return `${usedDisplay} is not an ${entry.usedAs} in ${standard} — it exists as ${actualDisplay}.`;
}

// Docs request ("Servicio de fichas de esquema y su uso en Ask"): which
// names to request a schema CARD for, from a given text -- reusing the
// EXACT same deterministic extraction the vocabulary-warning banner
// already uses (explicit `<x>`/`@x` markup, camelCase, and phrase-triggered
// words), restricted to names that actually EXIST in the vocabulary (an
// inexistent name already has its own red warning; it never gets a schema
// card, there is nothing real to fetch). This is also, by construction,
// how the encargo's own "no cards for bare words that coincidentally match
// a schema name" requirement is satisfied: extractContextCandidates never
// treats an untriggered, unmarked bare word (e.g. "para", "note" used as
// ordinary Spanish/English words) as a candidate AT ALL -- there is no
// "scan every word against the vocabulary" step to begin with, so nothing
// extra is needed here.
//
// ELEMENT names only: the generator ("una ficha por elemento", docs
// request point 1) never produces a card for a bare attribute -- an
// attribute's own facts (required/enum) only exist as part of whichever
// element card declares it. A `@frame` mentioned on its own therefore
// never gets its own fetch; its information already surfaces inside the
// `<table>` card wherever `<table>` itself is a selected name.
export function extractSchemaFactCandidates(text, vocabulary) {
  if (!vocabulary) return [];
  const { elements, camelCase, phraseCandidates } = extractContextCandidates(text);
  const results = [];
  const seen = new Set();
  const add = (name) => {
    if (seen.has(name)) return;
    seen.add(name);
    results.push({ name, type: 'element' });
  };
  for (const name of elements) if (vocabulary.elements.has(name)) add(name);
  for (const name of camelCase) if (vocabulary.elements.has(name)) add(name);
  for (const r of resolvePhraseCandidates(phraseCandidates, vocabulary)) {
    if (r.type === 'element') add(r.name);
  }
  return results;
}

// Selects up to `max` names across several texts, in PRIORITY ORDER (the
// encargo's own wording: "priorizando los de la pregunta y luego los del
// Title" -- Definition/Proposal are extracted too, per the encargo's
// "aplicada... a Title/Definition/Proposal", but at lower priority still,
// after Title, since only those two are named explicitly as the priority
// pair). Dedupes across texts (a name mentioned in both the question and
// the Title only ever asks for one card, keeping its higher priority).
export function selectSchemaFactNames(orderedTexts, vocabulary, max = 6) {
  if (!vocabulary) return [];
  const seen = new Set();
  const selected = [];
  for (const text of orderedTexts) {
    if (selected.length >= max) break;
    for (const candidate of extractSchemaFactCandidates(text, vocabulary)) {
      if (selected.length >= max) break;
      if (seen.has(candidate.name)) continue;
      seen.add(candidate.name);
      selected.push(candidate);
    }
  }
  return selected;
}

// A cheap, stable, non-cryptographic hash of the three text fields --
// only used as an in-memory key to avoid recomputing when nothing changed,
// never for anything security-sensitive.
export function hashVocabInputText(title, definition, proposal) {
  const s = `${title || ''}\u0000${definition || ''}\u0000${proposal || ''}`;
  let hash = 0;
  for (let i = 0; i < s.length; i++) {
    hash = (Math.imul(hash, 31) + s.charCodeAt(i)) | 0;
  }
  return hash.toString(36);
}

// ═══ 2. XPath expressions of a rule ════════════════════════════════════════

// Suggest Rule validation (docs request, Suggest Rule round, Part 4):
// deterministic, only ever WARNS, never blocks. Pulls the element and
// attribute names a rule's XPath expressions actually reference and checks
// them against the standard's real schema vocabulary (the same
// public/schema-vocabulary-*.json the BRDP text check uses), so an invented
// element in a generated -- or hand-pasted -- rule is flagged before it is
// saved as Draft.
//
// Where the XPath lives, per format:
//   BREX 4.2/4.1 -> <objectPath> text      BREX 3.0.1 -> <objpath> text
//   Schematron   -> @context and @test (sch:rule / sch:assert / sch:report,
//                   with or without the sch: prefix)
//
// Pure string processing (no DOMParser) so it runs the same under plain
// Node for scripts/test-rule-name-check.mjs.

const XML_ENTITIES = { lt: '<', gt: '>', amp: '&', quot: '"', apos: "'" };

function decodeEntities(text) {
  return text.replace(/&(lt|gt|amp|quot|apos);/g, (_, name) => XML_ENTITIES[name]);
}

const TEXT_PATH_RE = /<(objectPath|objpath)\b[^>]*>([\s\S]*?)<\/\1>/g;
const SCH_ATTR_RE = /<(?:[A-Za-z_][\w.-]*:)?(?:rule|assert|report)\b([^>]*)>/g;
const CONTEXT_TEST_ATTR_RE = /\s(context|test)\s*=\s*("([^"]*)"|'([^']*)')/g;

// Every XPath expression in a rule fragment, entity-decoded.
export function extractRuleXPaths(ruleXml) {
  const source = ruleXml || '';
  const out = [];
  let m;
  TEXT_PATH_RE.lastIndex = 0;
  while ((m = TEXT_PATH_RE.exec(source))) out.push(decodeEntities(m[2].trim()));
  SCH_ATTR_RE.lastIndex = 0;
  while ((m = SCH_ATTR_RE.exec(source))) {
    let a;
    CONTEXT_TEST_ATTR_RE.lastIndex = 0;
    while ((a = CONTEXT_TEST_ATTR_RE.exec(m[1]))) {
      out.push(decodeEntities(a[3] !== undefined ? a[3] : a[4]));
    }
  }
  return out.filter(Boolean);
}

// XPath 2.0/3.0 operator/keyword words. Only treated as operators when they
// are NOT in a path-step position (see extractXPathNames) -- "//map" is
// DITA's real <map> element, "a map b" never happens.
const XPATH_KEYWORDS = new Set([
  'and', 'or', 'div', 'idiv', 'mod', 'eq', 'ne', 'lt', 'le', 'gt', 'ge', 'is',
  'if', 'then', 'else', 'for', 'let', 'in', 'return', 'some', 'every', 'satisfies',
  'as', 'instance', 'of', 'treat', 'cast', 'castable', 'to', 'union', 'intersect', 'except',
]);

const NAME_START = /[A-Za-z_]/;
const NAME_CHAR = /[\w.-]/;

// Element/attribute names referenced by ONE XPath expression. Ignored:
// string literals, variables ($x), function calls and kind tests (a name
// followed by "("), axes (name followed by "::"), wildcards, numbers,
// operator keywords, and any namespace-prefixed name (xs:string, fn:head,
// sch:..., xlink:href) -- the vocabulary is unprefixed local names, and a
// prefixed token is far more often a type or function than a schema name,
// so checking it would only produce false red warnings.
export function extractXPathNames(xpath) {
  const src = xpath || '';
  const elements = new Set();
  const attributes = new Set();
  let i = 0;
  let prevSignificant = ''; // last non-space character consumed
  let pendingAttributeAxis = false;

  const peekNonSpace = (from) => {
    let j = from;
    while (j < src.length && /\s/.test(src[j])) j++;
    return j;
  };

  while (i < src.length) {
    const ch = src[i];
    if (/\s/.test(ch)) {
      i++;
      continue;
    }
    if (ch === '"' || ch === "'") {
      const close = src.indexOf(ch, i + 1);
      i = close === -1 ? src.length : close + 1;
      prevSignificant = ch;
      continue;
    }
    if (ch === '$') {
      i++;
      while (i < src.length && (NAME_CHAR.test(src[i]) || src[i] === ':')) i++;
      prevSignificant = 'v';
      continue;
    }
    if (/[0-9]/.test(ch) || (ch === '.' && /[0-9]/.test(src[i + 1] || ''))) {
      i++;
      while (i < src.length && /[0-9.eE]/.test(src[i])) i++;
      prevSignificant = '0';
      continue;
    }
    if (NAME_START.test(ch)) {
      const start = i;
      while (i < src.length && NAME_CHAR.test(src[i])) i++;
      let name = src.slice(start, i);
      // A trailing "." or "-" is never part of a name here ("a -1", "x.").
      while (/[.-]$/.test(name)) {
        name = name.slice(0, -1);
        i--;
      }
      let prefixed = false;
      if (src[i] === ':' && src[i + 1] !== ':' && NAME_START.test(src[i + 1] || '')) {
        prefixed = true;
        i++;
        while (i < src.length && NAME_CHAR.test(src[i])) i++;
      }
      const next = peekNonSpace(i);
      const isAxis = src[next] === ':' && src[next + 1] === ':';
      const isCall = src[next] === '(';
      const afterAt = prevSignificant === '@';
      const inStepPosition = prevSignificant === '' || '/@[(,|:'.includes(prevSignificant);
      // "for $x in", "some $r in", "let $v :=" -- a keyword binding a
      // variable is always an operator, even at the start of the path.
      const isOperator = XPATH_KEYWORDS.has(name) && (!inStepPosition || src[next] === '$');

      if (isAxis) {
        pendingAttributeAxis = name === 'attribute';
        i = next + 2;
        prevSignificant = ':';
        continue;
      }
      if (!prefixed && !isCall && !isOperator) {
        if (afterAt || pendingAttributeAxis) attributes.add(name);
        else elements.add(name);
      }
      pendingAttributeAxis = false;
      prevSignificant = 'n';
      continue;
    }
    // Any other punctuation: operators, brackets, "/", "@", "*", "|", ",".
    if (ch !== '*') pendingAttributeAxis = false;
    prevSignificant = ch;
    i++;
  }
  return { elements: [...elements], attributes: [...attributes] };
}

// All names referenced by a whole rule fragment.
export function extractRuleNames(ruleXml) {
  const elements = new Set();
  const attributes = new Set();
  for (const xpath of extractRuleXPaths(ruleXml)) {
    const names = extractXPathNames(xpath);
    names.elements.forEach((n) => elements.add(n));
    names.attributes.forEach((n) => attributes.add(n));
  }
  return { elements: [...elements].sort(), attributes: [...attributes].sort() };
}

// Same result shape as checkAgainstVocabulary ({available, notFound,
// wrongType}), so the UI renders it with the exact same red warning.
export function checkRuleNames(ruleXml, vocabulary) {
  const { elements, attributes } = extractRuleNames(ruleXml);
  return checkAgainstVocabulary({ elements, attributes, camelCase: [] }, vocabulary);
}

// ═══ 2. Ask answers ════════════════════════════════════════════════════════

// "Ask: comprobar los nombres de la respuesta" round, Part 1: after Ask's
// answer arrives, the element/attribute names it mentions are checked
// deterministically against the project standard's vocabulary -- the same
// vocabulary and the same checkAgainstVocabulary the BRDP's own red notice
// uses. Only warns (the caller shows a red line under the answer); never
// edits or hides the answer. Pure and framework-free, so the Node test
// scripts import it directly.
//
// Real case behind it (S1000D 3.0.1): the BRDP says `@ncage` (correctly
// flagged: no such attribute in 3.0.1), and "¿Cuál es el elemento usado
// para Ncage?" got "ncage es un atributo del elemento
// `<identAndStatusSection>`" -- `<identAndStatusSection>` is 4.x only
// (3.0.1 uses `<idstatus>`).
//
// "Aviso de nombres sin heurísticas" round: the check no longer tries to
// read sentences. The first version skipped names the answer denied ("no
// existe", "instead of", ...) and matched the BRDP's own nonexistent names
// even when written bare; against real Mistral answers that guessed wrong
// in both directions ("The attribute **@ncage** does not exist" and "does
// not contain ... including @ncage" were read as claims that it exists).
// Now:
//   - the names the BRDP's own notice already reports (its notFound /
//     wrongType, the list the prompt receives) are never checked in the
//     answer -- the user has already been warned about them, and an
//     answer that repeats them is usually saying they do not exist;
//   - every other name the answer mentions is checked as written, with no
//     interpretation of the sentence around it; the warning text is
//     neutral ("names mentioned in the answer that do not exist ...").
//
// What counts as a name in the answer:
//   - the existing extractor (extractContextCandidates): `<x>` tags,
//     half-typed `<x`/`x>`, `@x`, and camelCase words;
//   - a name inside inline code (`x`) that sits next to an element/
//     attribute word ("el atributo `ncage`", "the `ncage` attribute"),
//     which gives its kind. A bare code token with no such word is
//     ignored: in an answer it is as often an attribute VALUE (`em01`) or
//     a keyword as a name, and guessing would produce false warnings.
// Names with a namespace prefix (`<xsl:template>`, `@xlink:href`) are
// never schema vocabulary and are skipped.

const CODE_SPAN_RE = /`([^`\n]+)`/g;
const CODE_NAME_RE = /^(@)?<?\/?([A-Za-z][\w.-]*)>?$/;
const KIND_WORDS = {
  element: ['elemento', 'elementos', 'element', 'elements', 'etiqueta', 'etiquetas', 'tag', 'tags'],
  attribute: ['atributo', 'atributos', 'attribute', 'attributes'],
};
const CONNECTORS = new Set(['el', 'la', 'los', 'las', 'del', 'de', 'un', 'una', 'the', 'of', 'a', 'an']);

function kindOfWord(word) {
  const w = (word || '').toLowerCase();
  if (KIND_WORDS.element.includes(w)) return 'element';
  if (KIND_WORDS.attribute.includes(w)) return 'attribute';
  return null;
}

// The element/attribute word right before a code span (skipping
// articles/prepositions) or right after it.
function kindAround(text, start, end) {
  const before = text.slice(Math.max(0, start - 40), start).match(/[\p{L}]+/gu) || [];
  for (let i = before.length - 1; i >= 0 && i >= before.length - 3; i--) {
    const kind = kindOfWord(before[i]);
    if (kind) return kind;
    if (!CONNECTORS.has(before[i].toLowerCase())) break;
  }
  const after = text.slice(end, end + 20).match(/^\s*([\p{L}]+)/u);
  return after ? kindOfWord(after[1]) : null;
}

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Deterministic candidates in the answer text: { elements, attributes,
// camelCase } in the shape checkAgainstVocabulary takes.
export function extractAnswerNames(text) {
  const source = text || '';
  const base = extractContextCandidates(source);
  const elements = new Set(base.elements);
  const attributes = new Set(base.attributes);
  let m;
  CODE_SPAN_RE.lastIndex = 0;
  while ((m = CODE_SPAN_RE.exec(source))) {
    const code = m[1].trim();
    const nm = code.match(CODE_NAME_RE);
    if (!nm) continue;
    const name = nm[2];
    // `<x>` and `@x` inside code are already taken by the extractor above.
    if (nm[1] || code.startsWith('<')) continue;
    const kind = kindAround(source, m.index, m.index + m[0].length);
    if (kind === 'element') elements.add(name);
    else if (kind === 'attribute') attributes.add(name);
  }
  // The prefix of `<xsl:template>` / `@xlink:href`, or the local part of
  // `<xsl:template>` (which the half-typed-tag reader sees as `template>`).
  const prefixed = (name, marker) =>
    new RegExp(`${marker}${escapeRegExp(name)}:|[\\w-]:${escapeRegExp(name)}(?![\\w-])`).test(source);
  return {
    elements: [...elements].filter((n) => !prefixed(n, '</?')),
    attributes: [...attributes].filter((n) => !prefixed(n, '@')),
    camelCase: base.camelCase,
  };
}

const bareName = (display) => display.replace(/^[<@]|>$/g, '');

// Returns { available, notFound: ["<x>", "@y", ...], wrongType: [{ name,
// usedAs, actualAs }] } -- the same shapes as checkAgainstVocabulary, so
// the UI formats them the same way. `brdpVocabCheck` is the BRDP's own
// vocabulary result ({ notFound, wrongType }, what the prompt receives);
// its names are left out of the answer check.
export function checkAnswerNames(answerText, vocabulary, brdpVocabCheck = null) {
  if (!vocabulary) return { available: false, notFound: [], wrongType: [] };
  const alreadyWarned = new Set([
    ...(brdpVocabCheck?.notFound || []).map(bareName),
    ...(brdpVocabCheck?.wrongType || []).map((w) => w.name),
  ]);
  const checked = checkAgainstVocabulary(extractAnswerNames(answerText || ''), vocabulary);
  return {
    available: true,
    notFound: checked.notFound.filter((display) => !alreadyWarned.has(bareName(display))),
    wrongType: checked.wrongType.filter((w) => !alreadyWarned.has(w.name)),
  };
}

// Whether the check found anything to warn about.
export function answerNameCheckHasWarnings(result) {
  return Boolean(result && result.available && (result.notFound.length > 0 || result.wrongType.length > 0));
}

// ═══ 2. XML documents (Test rule examples) ═════════════════════════════════

// The element and attribute names of a parsed XML document (no prefixed
// names, no xmlns) -- what the Test rule checks against the vocabulary.
export function extractDocumentNames(doc) {
  const elements = new Set();
  const attributes = new Set();
  const walk = (el) => {
    if (!String(el.nodeName).includes(':')) elements.add(el.nodeName);
    for (const a of Array.from(el.attributes || [])) {
      if (!a.name.includes(':') && a.name !== 'xmlns') attributes.add(a.name);
    }
    for (let n = el.firstChild; n; n = n.nextSibling) if (n.nodeType === 1) walk(n);
  };
  walk(doc.documentElement);
  return { elements: [...elements], attributes: [...attributes], camelCase: [] };
}

// ═══ 4. Structure ══════════════════════════════════════════════════════════

// ─── Structural check ───────────────────────────────────────────────────────

// [{ kind: 'unknownElement', element } | { kind: 'notAllowed', element, parent }
//  | { kind: 'unknownAttribute', attribute, element } | { kind: 'wrongRoot', element, expected }]
// against one schema's structure. Prefixed attributes other than xlink:* and
// namespace declarations are not schema vocabulary and are left out.
export function checkExampleStructure(doc, structure) {
  const elements = structure.elements;
  const problems = [];
  const seen = new Set();
  const add = (problem) => {
    const key = JSON.stringify(problem);
    if (!seen.has(key)) {
      seen.add(key);
      problems.push(problem);
    }
  };
  const root = doc.documentElement;
  if (structure.skeleton && root.nodeName !== structure.skeleton.root) {
    add({ kind: 'wrongRoot', element: root.nodeName, expected: structure.skeleton.root });
  }
  const walk = (el, parentName) => {
    const name = el.nodeName;
    const known = Boolean(elements[name]);
    if (!known) add({ kind: 'unknownElement', element: name });
    else if (parentName && elements[parentName] && !elements[parentName].children.includes(name)) {
      add({ kind: 'notAllowed', element: name, parent: parentName });
    }
    if (known) {
      for (const a of Array.from(el.attributes || [])) {
        if (a.name === 'xmlns' || a.name.startsWith('xmlns:') || a.name.startsWith('xsi:')) continue;
        if (a.name.includes(':') && !a.name.startsWith('xlink:')) continue;
        const local = a.name.replace(/^xlink:/, '');
        if (!elements[name].attributes.includes(local)) add({ kind: 'unknownAttribute', attribute: a.name, element: name });
      }
    }
    for (let n = el.firstChild; n; n = n.nextSibling) if (n.nodeType === 1) walk(n, name);
  };
  walk(root, null);
  return problems;
}

// ─── CALS table spans (C3, Part 1b) ────────────────────────────────────────

// CALS tables (S1000D and DITA use the same model): an <entry
// morerows="N"> also occupies its column(s) in the next N rows of its
// thead/tbody/tfoot, so those rows must not have an entry of their own
// there. An LLM writing examples often adds one anyway. The schema
// structure cannot see this (every element is allowed where it is), so it
// is checked here:
//   { kind: 'spannedEntry', row, column }   -- row N has an entry in a
//                                             column spanned from above
//   { kind: 'morerowsPastEnd', row, column } -- the span of row N's entry
//                                             runs past the last row
//   { kind: 'rowFullyCovered', row }        -- every entry of row N sits in
//                                             a spanned column (or the row
//                                             has none and is fully spanned):
//                                             removing them would leave an
//                                             empty <row>, so this replaces
//                                             the row's spannedEntry problems
//   { kind: 'emptyRow', row }               -- row N has no <entry> and
//                                             is not fully covered from
//                                             above (CALS needs at least one)
// `row` is 1-based within its thead/tbody/tfoot; `column` is the colspec's
// colname, or c1, c2… by position when the table has no colspecs.
// Columns come from @colname / @namest–@nameend when the entry has them
// (checked against the spans directly), otherwise by position: an entry
// without a name takes the next column in reading order, ignoring spans the
// way a writer who forgot them would -- so, when a row has more entries than
// its free columns, the entries sitting in spanned columns are the extra
// ones. Never throws: an unknown colname is treated as positional.
export function checkCalsTableSpans(doc) {
  return calsSpanProblems(doc).map(({ entry, ...problem }) => problem);
}

// Same walk, keeping the offending <entry> of each spannedEntry problem.
function calsSpanProblems(doc) {
  const problems = [];
  const childrenNamed = (el, name) => Array.from(el.childNodes || []).filter((n) => n.nodeType === 1 && n.nodeName === name);
  const intAttr = (el, name) => {
    const n = Number.parseInt(el.getAttribute(name) || '', 10);
    return Number.isFinite(n) && n > 0 ? n : 0;
  };
  const tgroups = Array.from(doc.getElementsByTagName('tgroup'));
  for (const tgroup of tgroups) {
    const colspecs = childrenNamed(tgroup, 'colspec');
    const colIndex = new Map();
    colspecs.forEach((c, i) => {
      const name = c.getAttribute('colname');
      if (name && !colIndex.has(name)) colIndex.set(name, i);
    });
    const label = (i) => colspecs[i]?.getAttribute('colname') || `c${i + 1}`;
    for (const sectionName of ['thead', 'tbody', 'tfoot']) {
      for (const section of childrenNamed(tgroup, sectionName)) {
        const rows = childrenNamed(section, 'row');
        const declared = intAttr(tgroup, 'cols') || colspecs.length;
        // Without @cols or colspecs, the first row (nothing spans into it)
        // gives the width.
        const cols = declared || (rows[0] ? childrenNamed(rows[0], 'entry').length : 0);
        const spanned = rows.map(() => new Set());
        rows.forEach((row, r) => {
          const entries = childrenNamed(row, 'entry');
          const named = (entry) => {
            const start = colIndex.get(entry.getAttribute('colname') || entry.getAttribute('namest'));
            if (start === undefined) return null;
            const end = colIndex.get(entry.getAttribute('nameend'));
            return { start, end: end !== undefined && end >= start ? end : start };
          };
          const free = cols - spanned[r].size;
          const overfull = entries.length > free;
          const rowProblems = [];
          let cursor = 0;
          entries.forEach((entry, e) => {
            let span = named(entry);
            if (!span) {
              if (overfull) {
                // Position as written: entry e sits in column e.
                span = { start: e, end: e };
              } else {
                while (spanned[r].has(cursor)) cursor += 1;
                span = { start: cursor, end: cursor };
              }
            }
            cursor = span.end + 1;
            for (let c = span.start; c <= span.end; c += 1) {
              if (spanned[r].has(c)) {
                rowProblems.push({ kind: 'spannedEntry', row: r + 1, column: label(c), entry });
                break;
              }
            }
            const more = intAttr(entry, 'morerows');
            for (let k = 1; k <= more; k += 1) {
              if (r + k >= rows.length) {
                rowProblems.push({ kind: 'morerowsPastEnd', row: r + 1, column: label(span.start) });
                break;
              }
              for (let c = span.start; c <= span.end; c += 1) spanned[r + k].add(c);
            }
          });
          const spannedCount = rowProblems.filter((p) => p.kind === 'spannedEntry').length;
          const fullyCovered = entries.length > 0 ? spannedCount === entries.length : cols > 0 && spanned[r].size >= cols;
          if (fullyCovered) {
            problems.push({ kind: 'rowFullyCovered', row: r + 1 }, ...rowProblems.filter((p) => p.kind !== 'spannedEntry'));
          } else if (entries.length === 0) {
            problems.push({ kind: 'emptyRow', row: r + 1 });
          } else {
            problems.push(...rowProblems);
          }
        });
      }
    }
  }
  return problems;
}

// C3b: an <entry> in a column a morerows above already covers is always an
// error, and the fix is always the same -- remove that entry. The
// application does it itself, on the LLM's content, before any correction
// round (a real run, titled-context at 297df74, sent two such tables back
// to the LLM and got them back unchanged). `content` is the example's
// content (one or several root elements); the entries are removed from the
// TEXT, so the rest stays exactly as written. Repeats until no entry sits
// in a spanned column (removing one can shift the next row's reading),
// then returns { content, removedRows: [row numbers, in order] }. Content
// that does not parse is returned unchanged -- its validation reports it.
// morerows running past the last row is not touched: that one has no
// single right fix and still goes to the LLM. Neither is an example with a
// row entirely covered from above (rowFullyCovered): removing its entries
// would leave an empty <row>, so nothing in that example is adjusted and
// the problem goes to the correction round.
const TAG_TOKEN_RE = /<!--[\s\S]*?-->|<!\[CDATA\[[\s\S]*?\]\]>|<\?[\s\S]*?\?>|<(\/?)([A-Za-z_][\w.:-]*)((?:\s+[^\s=/>]+\s*=\s*(?:"[^"]*"|'[^']*'))*)\s*(\/?)>/g;

// [start, end) of the Nth <entry> element (0-based, document order) in text.
function entrySpans(text) {
  const spans = [];
  const open = [];
  for (const m of text.matchAll(TAG_TOKEN_RE)) {
    if (m[2] === undefined || m[2] !== 'entry') continue;
    if (m[1]) {
      const index = open.pop();
      if (index !== undefined) spans[index].end = m.index + m[0].length;
    } else if (m[4]) {
      spans.push({ start: m.index, end: m.index + m[0].length });
    } else {
      open.push(spans.length);
      spans.push({ start: m.index, end: null });
    }
  }
  return spans;
}

export function removeSpannedCalsEntries(content, parseXml) {
  const original = String(content ?? '');
  let text = original;
  const removedRows = [];
  for (let pass = 0; pass < 10; pass += 1) {
    let doc;
    try {
      doc = parseXml(wrapRuleXmlFragment(text));
      if (!doc?.documentElement) break;
    } catch {
      break;
    }
    const problems = calsSpanProblems(doc);
    if (problems.some((p) => p.kind === 'rowFullyCovered')) return { content: original, removedRows: [] };
    const offending = problems.filter((p) => p.kind === 'spannedEntry');
    if (offending.length === 0) break;
    const allEntries = Array.from(doc.getElementsByTagName('entry'));
    const spans = entrySpans(text);
    if (spans.length !== allEntries.length) break; // text and DOM disagree: leave it
    const cuts = [];
    for (const p of offending) {
      const span = spans[allEntries.indexOf(p.entry)];
      if (!span || span.end === null) continue;
      let start = span.start;
      // Take the entry's own indentation (and line) with it.
      while (start > 0 && (text[start - 1] === ' ' || text[start - 1] === '\t')) start -= 1;
      if (start > 0 && text[start - 1] === '\n') start -= 1;
      cuts.push({ start, end: span.end });
      removedRows.push(p.row);
    }
    if (cuts.length === 0) break;
    // An entry inside another removed entry goes with it.
    const outer = cuts.filter((c) => !cuts.some((o) => o !== c && o.start <= c.start && c.end <= o.end));
    for (const cut of outer.sort((a, b) => b.start - a.start)) text = text.slice(0, cut.start) + text.slice(cut.end);
  }
  return { content: text, removedRows };
}

// ─── Missing CALS colspecs (C3b follow-up) ─────────────────────────────────
// An <entry colname="c2"> only means something if its <tgroup> has a
// <colspec colname="c2"/>; an LLM often writes the colnames and no colspec
// at all (the EXT-00001 run of 29/09: every table used c1/c2/c3 with no
// <colspec>). Like the morerows fix, the application adds them itself when
// the fix is unambiguous: one <colspec> per colname used (@colname, @namest,
// @nameend of the tgroup's own entries) that has none, placed in column
// order at the start of the <tgroup>, among the colspecs already there
// (never touched). A name's column comes from its number: c3, col3,
// column3, col-3 or a bare 3 are column 3 (the only forms read -- a name
// like "part" gives no column). Existing colspecs keep their CALS column
// (@colnum, or the previous one + 1). A new colspec gets @colnum only when
// its column does not follow the previous one (a gap), so c1/c2/c3 get the
// plain <colspec colname="cX"/>.
// Not adjusted -- the example goes to the correction round with the reason:
//   { kind: 'unorderableColname', colname } -- no column can be worked out
//                        (no number, column 0, or a column already taken
//                        by another colspec or colname)
//   { kind: 'tooManyColumns', columns, cols } -- the tgroup uses more
//                        distinct columns (or a higher column) than its @cols
// Either problem anywhere in the example leaves the whole example as
// written (same as rowFullyCovered for morerows).
const COLNAME_POSITION_RE = /^(?:c|col|column)?[-_]?(\d+)$/i;

function calsColspecPlans(doc) {
  const childrenNamed = (el, name) => Array.from(el.childNodes || []).filter((n) => n.nodeType === 1 && n.nodeName === name);
  const allColspecs = Array.from(doc.getElementsByTagName('colspec'));
  return Array.from(doc.getElementsByTagName('tgroup')).map((tgroup) => {
    const problems = [];
    const existing = [];
    let prev = 0;
    for (const c of childrenNamed(tgroup, 'colspec')) {
      const colnum = Number.parseInt(c.getAttribute('colnum') || '', 10);
      const position = Number.isFinite(colnum) && colnum > 0 ? colnum : prev + 1;
      prev = position;
      existing.push({ name: c.getAttribute('colname') || '', position, index: allColspecs.indexOf(c) });
    }
    const declared = new Set(existing.map((c) => c.name).filter(Boolean));
    const used = [];
    for (const section of ['thead', 'tbody', 'tfoot'].flatMap((n) => childrenNamed(tgroup, n))) {
      for (const row of childrenNamed(section, 'row')) {
        for (const entry of childrenNamed(row, 'entry')) {
          for (const attr of ['colname', 'namest', 'nameend']) {
            const name = entry.getAttribute(attr);
            if (name && !used.includes(name)) used.push(name);
          }
        }
      }
    }
    const taken = new Set(existing.map((c) => c.position));
    const missing = [];
    for (const name of used.filter((n) => !declared.has(n))) {
      const m = COLNAME_POSITION_RE.exec(name);
      const position = m ? Number.parseInt(m[1], 10) : 0;
      if (!position || taken.has(position)) {
        problems.push({ kind: 'unorderableColname', colname: name });
        continue;
      }
      taken.add(position);
      missing.push({ name, position });
    }
    const cols = Number.parseInt(tgroup.getAttribute('cols') || '', 10);
    if (Number.isFinite(cols) && cols > 0) {
      const distinct = new Set([...existing.map((c) => c.name || `#${c.position}`), ...used]).size;
      const columns = Math.max(distinct, ...existing.map((c) => c.position), ...missing.map((c) => c.position), 0);
      if (columns > cols) problems.push({ kind: 'tooManyColumns', columns, cols });
    }
    missing.sort((a, b) => a.position - b.position);
    return { tgroup, existing, missing, problems };
  });
}

// Problems the application cannot fix itself (see above); reported by
// validateExample so they reach the correction round.
export function checkCalsColspecs(doc) {
  return calsColspecPlans(doc).flatMap((plan) => plan.problems);
}

// [start, end) of every <name> element (document order) in text; end is
// null for an unclosed one.
function elementSpans(text, name) {
  const spans = [];
  const open = [];
  for (const m of text.matchAll(TAG_TOKEN_RE)) {
    if (m[2] === undefined || m[2] !== name) continue;
    if (m[1]) {
      const index = open.pop();
      if (index !== undefined) spans[index].end = m.index + m[0].length;
    } else if (m[4]) {
      spans.push({ start: m.index, end: m.index + m[0].length, openEnd: m.index + m[0].length });
    } else {
      open.push(spans.length);
      spans.push({ start: m.index, end: null, openEnd: m.index + m[0].length });
    }
  }
  return spans;
}

// Adds the missing colspecs to the TEXT of `content` (the rest stays exactly
// as written) → { content, added }. Unchanged (added 0) when nothing is
// missing, when any tgroup has an unfixable problem, or when the content
// does not parse or its text and DOM disagree.
export function addMissingCalsColspecs(content, parseXml) {
  const original = String(content ?? '');
  let doc;
  try {
    doc = parseXml(wrapRuleXmlFragment(original));
    if (!doc?.documentElement) return { content: original, added: 0 };
  } catch {
    return { content: original, added: 0 };
  }
  const plans = calsColspecPlans(doc);
  if (plans.some((p) => p.problems.length > 0)) return { content: original, added: 0 };
  if (!plans.some((p) => p.missing.length > 0)) return { content: original, added: 0 };
  const tgroupSpans = elementSpans(original, 'tgroup');
  const colspecSpans = elementSpans(original, 'colspec');
  if (tgroupSpans.length !== plans.length || colspecSpans.length !== doc.getElementsByTagName('colspec').length) {
    return { content: original, added: 0 };
  }
  const inserts = [];
  let added = 0;
  plans.forEach((plan, t) => {
    if (plan.missing.length === 0) return;
    const openEnd = tgroupSpans[t].openEnd;
    const lineBreak = /^\r?\n([ \t]*)/.exec(original.slice(openEnd));
    const format = (tag) => (lineBreak ? `\n${lineBreak[1]}${tag}` : tag);
    // Final order: existing and new colspecs by column; a new one goes after
    // the tgroup's open tag or after the existing colspec before it.
    const byAnchor = new Map();
    let prevPosition = 0;
    let anchor = openEnd;
    const sequence = [...plan.existing.map((c) => ({ ...c, existing: true })), ...plan.missing].sort((a, b) => a.position - b.position);
    for (const col of sequence) {
      if (col.existing) {
        const span = colspecSpans[col.index];
        if (!span || span.end === null) return;
        anchor = span.end;
      } else {
        const colnum = col.position === prevPosition + 1 ? '' : ` colnum="${col.position}"`;
        const list = byAnchor.get(anchor) || [];
        list.push(format(`<colspec colname="${col.name}"${colnum}/>`));
        byAnchor.set(anchor, list);
        added += 1;
      }
      prevPosition = col.position;
    }
    for (const [at, tags] of byAnchor) inserts.push({ at, text: tags.join('') });
  });
  let text = original;
  for (const ins of inserts.sort((a, b) => b.at - a.at)) text = text.slice(0, ins.at) + ins.text + text.slice(ins.at);
  return { content: text, added };
}

// English, for the correction request sent back to the LLM (the panel
// translates the same problems through i18n).
export function formatStructureProblem(problem, schema) {
  switch (problem.kind) {
    case 'spannedEntry':
      return `row ${problem.row}: column ${problem.column} is already spanned by the entry above (morerows); remove this entry`;
    case 'morerowsPastEnd':
      return `row ${problem.row}: morerows spans past the last row (column ${problem.column})`;
    case 'emptyRow':
      return `row ${problem.row} has no entry`;
    case 'rowFullyCovered':
      return `row ${problem.row} is entirely covered by morerows from above: give row ${problem.row} its own entries or lower the morerows`;
    case 'unorderableColname':
      return `colname="${problem.colname}" has no <colspec> and its column cannot be worked out: add <colspec colname="${problem.colname}"/> to the <tgroup>, in column order`;
    case 'tooManyColumns':
      return `the table uses ${problem.columns} columns but its <tgroup> says cols="${problem.cols}": use at most ${problem.cols} columns or raise cols`;
    case 'unknownElement':
      return `<${problem.element}> does not exist in the ${schema} schema`;
    case 'notAllowed':
      return `<${problem.element}> is not allowed inside <${problem.parent}>`;
    case 'unknownAttribute':
      return `@${problem.attribute} does not exist on <${problem.element}>`;
    case 'wrongRoot':
      return `the root element is <${problem.element}>, not <${problem.expected}>`;
    default:
      return String(problem.kind);
  }
}

// ═══ 5. XPath syntax ═══════════════════════════════════════════════════════

// Suggest Rule validation -- XPath syntax (schema-location encargo, Part 3).
// A real Mistral run wrote <objectPath>//&lt;emphasis&gt;</objectPath>: the
// name check (ruleNameCheck.js) extracts "emphasis", which IS a real 4.2
// element, so nothing was flagged -- the expression itself is not XPath.
// This checks that every XPath expression of a rule (objectPath/objpath in
// BREX, @context and @test in Schematron -- extractRuleXPaths(), already
// entity-decoded) parses.
//
// Parser: fontoxpath (XPath 3.1), the same code in the browser and in plain
// Node (scripts/run-prompt-eval.mjs's xpath_valid check), so the app and the
// eval suite always agree. document.createExpression was not used: it is
// XPath 1.0 only and would reject valid DITA Schematron XPath 2.0/3.0
// (`every $r in … satisfies`, `('a','b')`, inline functions) and block
// Accept on correct rules. Consequence, accepted: XPath 2.0+ syntax in a
// BREX objectPath is not reported (only real syntax errors are).
//
// Only syntax errors count (XPST0003). Static errors that are normal in a
// rule fragment -- an undeclared $variable (sch:let), a prefix (xlink:,
// sch:, xs:) or a function this parser doesn't register (matches/3, doc) --
// and dynamic errors (no context item) never make an expression invalid.

const SYNTAX_ERROR = 'XPST0003';

export function isXPathSyntaxValid(expression) {
  try {
    fontoxpath.evaluateXPath(expression, null, null, null, fontoxpath.evaluateXPath.ANY_TYPE, {
      language: fontoxpath.evaluateXPath.XPATH_3_1_LANGUAGE,
    });
    return true;
  } catch (err) {
    return !String(err?.message || '').includes(SYNTAX_ERROR);
  }
}

// The rule's XPath expressions that are not syntactically valid (after
// undoing the XML escapes), in document order, without duplicates.
export function invalidRuleXPaths(ruleXml) {
  const invalid = [];
  for (const expression of extractRuleXPaths(ruleXml)) {
    if (!isXPathSyntaxValid(expression) && !invalid.includes(expression)) invalid.push(expression);
  }
  return invalid;
}

// ═══ 5b. Rule format ═══════════════════════════════════════════════════════

// Consolidation C2, Part 0: what is saved as a rule must contain a rule of
// the project's format. Real case: "Paste rule" with just the text
// //&lt;emphasis&gt; -- well-formed XML, no element at all -- was accepted,
// saved as Draft and could be tested. Checked on well-formed XML only (the
// well-formedness check runs first and reports its own error).
//
// What the top level of the fragment may hold, per format:
//   BREX 4.2/4.1  <structureObjectRule>, <nonContextRule>, or a
//                 <contextRules> block holding at least one structureObjectRule
//   BREX 3.0.1    <objrule>, a <contextrules> block holding at least one
//                 objrule, or the 3.0.1 stand-in for a rule without context:
//                 a comment starting with "nonContextRule" (the XSD has no
//                 nonContextRule element; Generate writes the comment)
//   SCH-DITA      <pattern> or <rule>, with or without a prefix
// Comments are always allowed next to the rule. Loose text and any other
// element are not; a wrapper around a rule (<rules>, a bare
// <structureObjectRuleGroup>) is reported as such, and a rule of another
// format (<sch:pattern> in a BREX project) says which format it belongs to.
// An unknown format is not checked. The backend applies the same check on
// PUT …/approvals/{format} (backend/app/services/rule_format_check.py --
// keep both in sync); the Excel import does not reject with it, but stores a
// rule without legacy wrappers (src/utils/ruleWrappers.js and its backend
// twin), and lint-curated-templates reports anything else.
const RULE_FORMAT_SHAPES = {
  'BREX-4.2': { label: 'BREX 4.2', rules: ['structureObjectRule', 'nonContextRule'], blocks: { contextRules: 'structureObjectRule' }, expected: 'structureObjectRule' },
  'BREX-4.1': { label: 'BREX 4.1', rules: ['structureObjectRule', 'nonContextRule'], blocks: { contextRules: 'structureObjectRule' }, expected: 'structureObjectRule' },
  'BREX-3.0.1': { label: 'BREX 3.0.1', rules: ['objrule'], blocks: { contextrules: 'objrule' }, expected: 'objrule', nonContextComment: true },
  'SCH-DITA': { label: 'Schematron (DITA)', rules: ['pattern', 'rule'], blocks: {}, expected: 'sch:pattern' },
};

// Element names that belong to one format only -- to say which format a
// misplaced rule element belongs to.
const RULE_ELEMENT_FORMAT = {
  structureObjectRule: 'BREX 4.x',
  nonContextRule: 'BREX 4.x',
  contextRules: 'BREX 4.x',
  structureObjectRuleGroup: 'BREX 4.x',
  objrule: 'BREX 3.0.1',
  contextrules: 'BREX 3.0.1',
  structrules: 'BREX 3.0.1',
  pattern: 'Schematron (DITA)',
  rule: 'Schematron (DITA)',
};

const TOP_LEVEL_TOKEN_RE =
  /<!--([\s\S]*?)-->|<\?[\s\S]*?\?>|<!\[CDATA\[([\s\S]*?)\]\]>|<!DOCTYPE[^>]*>|<(\/?)([^\s/>!?]+)(?:\s+[^\s=/>]+\s*=\s*(?:"[^"]*"|'[^']*'))*\s*(\/?)>/g;

const localNameOf = (qname) => qname.replace(/^.*:/, '');

// The top level of a well-formed fragment: elements (with the local names of
// their descendants), comments and loose text.
function scanTopLevel(xml) {
  const top = [];
  let depth = 0;
  let current = null;
  let last = 0;
  let m;
  const pushText = (text) => {
    if (depth === 0 && text.trim()) top.push({ kind: 'text', text: decodeEntities(text.trim()) });
  };
  TOP_LEVEL_TOKEN_RE.lastIndex = 0;
  while ((m = TOP_LEVEL_TOKEN_RE.exec(xml))) {
    pushText(xml.slice(last, m.index));
    last = TOP_LEVEL_TOKEN_RE.lastIndex;
    const [, comment, cdata, closing, name, selfClosing] = m;
    if (comment !== undefined) {
      if (depth === 0) top.push({ kind: 'comment', text: comment.trim() });
    } else if (cdata !== undefined) {
      pushText(cdata);
    } else if (name) {
      if (closing) {
        depth -= 1;
        if (depth === 0) current = null;
      } else if (depth === 0) {
        current = { kind: 'element', name, local: localNameOf(name), descendants: new Set() };
        top.push(current);
        if (!selfClosing) depth += 1;
        else current = null;
      } else {
        current?.descendants.add(localNameOf(name));
        if (!selfClosing) depth += 1;
      }
    }
  }
  pushText(xml.slice(last));
  return top;
}

// { checked, ok, problem: { code, params } | null } for a well-formed rule
// fragment. Codes: rule_format_other_format, rule_format_wrapper,
// rule_format_empty_block, rule_format_foreign, rule_format_missing,
// rule_format_text.
export function checkRuleFormat(ruleXml, format) {
  const shape = RULE_FORMAT_SHAPES[format];
  if (!shape) return { checked: false, ok: true, problem: null };
  const base = { format: shape.label, expected: shape.expected };
  const fail = (code, params = {}) => ({ checked: true, ok: false, problem: { code, params: { ...base, ...params } } });
  const top = scanTopLevel(ruleXml || '');
  let rules = 0;
  for (const node of top) {
    if (node.kind === 'comment') {
      if (shape.nonContextComment && /^nonContextRule\b/.test(node.text)) rules += 1;
      continue;
    }
    if (node.kind !== 'element') continue;
    if (shape.rules.includes(node.local)) {
      rules += 1;
      continue;
    }
    const inner = shape.blocks[node.local];
    if (inner) {
      if (!node.descendants.has(inner)) return fail('rule_format_empty_block', { element: node.name, inner });
      rules += 1;
      continue;
    }
    const otherFormat = RULE_ELEMENT_FORMAT[node.local];
    if (otherFormat && otherFormat !== shape.label && !(shape.label.startsWith('BREX 4') && otherFormat === 'BREX 4.x')) {
      return fail('rule_format_other_format', { element: node.name, otherFormat });
    }
    if (shape.rules.some((r) => node.descendants.has(r))) return fail('rule_format_wrapper', { element: node.name });
    return fail('rule_format_foreign', { element: node.name });
  }
  if (rules === 0) return fail('rule_format_missing');
  const text = top.find((n) => n.kind === 'text');
  if (text) return fail('rule_format_text', { text: text.text.length > 60 ? `${text.text.slice(0, 59)}…` : text.text });
  return { checked: true, ok: true, problem: null };
}

// checkRuleFormat's problem as issues (none when it passes).
export function ruleFormatIssues(result) {
  return result?.problem ? [{ source: 'rule', code: result.problem.code, params: result.problem.params }] : [];
}

// ═══ 6. Messages ═══════════════════════════════════════════════════════════

// Every finding as { source, code, params } -- never a finished sentence --
// so each panel translates it through one table (SCHEMA_ISSUE_KEYS) and one
// formatter (formatSchemaIssue). The keys are exactly the ones each panel
// used before this consolidation, so the texts on screen do not change.
// Sources: 'brdp' (the BRDP's own text), 'rule' (a suggested or pasted
// rule), 'answer' (an Ask answer), 'example' (a Test rule example).
export const SCHEMA_ISSUE_KEYS = {
  brdp: {
    names_not_found: 'records.assistant.vocabUnknownNames',
    name_did_you_mean: 'records.assistant.nameDidYouMean',
    name_other_standard: 'records.assistant.nameInOtherStandard',
    wrong_type_as_element: 'records.assistant.vocabWrongTypeAsElement',
    wrong_type_as_attribute: 'records.assistant.vocabWrongTypeAsAttribute',
  },
  rule: {
    names_not_found: 'records.assistant.ruleNamesNotFound',
    name_did_you_mean: 'records.assistant.nameDidYouMean',
    name_other_standard: 'records.assistant.nameInOtherStandard',
    wrong_type_as_element: 'records.assistant.vocabWrongTypeAsElement',
    wrong_type_as_attribute: 'records.assistant.vocabWrongTypeAsAttribute',
    invalid_xpath: 'records.assistant.ruleInvalidXPath',
    rule_format_missing: 'records.assistant.ruleFormat.missing',
    rule_format_text: 'records.assistant.ruleFormat.text',
    rule_format_wrapper: 'records.assistant.ruleFormat.wrapper',
    rule_format_empty_block: 'records.assistant.ruleFormat.emptyBlock',
    rule_format_other_format: 'records.assistant.ruleFormat.otherFormat',
    rule_format_foreign: 'records.assistant.ruleFormat.foreign',
  },
  answer: {
    names_not_found: 'records.assistant.answerUnknownNames',
    wrong_type_as_element: 'records.assistant.answerWrongTypeAsElement',
    wrong_type_as_attribute: 'records.assistant.answerWrongTypeAsAttribute',
  },
  example: {
    names_not_found: 'records.ruleTest.unknownNames',
    wrong_types: 'records.ruleTest.wrongTypeNames',
    unknownElement: 'records.ruleTest.structure.unknownElement',
    notAllowed: 'records.ruleTest.structure.notAllowed',
    unknownAttribute: 'records.ruleTest.structure.unknownAttribute',
    wrongRoot: 'records.ruleTest.structure.wrongRoot',
    spannedEntry: 'records.ruleTest.structure.spannedEntry',
    morerowsPastEnd: 'records.ruleTest.structure.morerowsPastEnd',
    rowFullyCovered: 'records.ruleTest.structure.rowFullyCovered',
    emptyRow: 'records.ruleTest.structure.emptyRow',
    unorderableColname: 'records.ruleTest.structure.unorderableColname',
    tooManyColumns: 'records.ruleTest.structure.tooManyColumns',
  },
};

// data-testids of the hint lines that follow a "not found" line.
export const NAME_HINT_TEST_IDS = { name_did_you_mean: 'name-did-you-mean', name_other_standard: 'name-other-standard' };

// A vocabulary result ({ available, notFound, wrongType } from
// checkAgainstVocabulary / checkRuleNames / checkAnswerNames) as issues.
// 'example' lists every wrong-type name in one issue, as its panel always
// did; the other sources give one issue per name. `hints` (nameFixHints,
// only for 'brdp' and 'rule') add one line per marked name after the
// "not found" line, which stays as it was.
export function nameIssues(result, source, { standard, hints = [] } = {}) {
  if (!result?.available) return [];
  const issues = [];
  if (result.notFound.length > 0) {
    issues.push({ source, code: 'names_not_found', params: { standard, names: result.notFound.join(', ') } });
  }
  for (const hint of hints) {
    const show = (n) => (hint.type === 'attribute' ? `@${n}` : `<${n}>`);
    if (hint.similar.length > 0) {
      issues.push({ source, code: 'name_did_you_mean', params: { name: show(hint.name), suggestions: hint.similar.map(show) } });
    } else if (hint.otherStandards.length > 0) {
      issues.push({
        source,
        code: 'name_other_standard',
        params: { name: show(hint.name), standard: vocabularyLabel(standard), standards: hint.otherStandards },
      });
    }
  }
  if (source === 'example') {
    if (result.wrongType.length > 0) {
      issues.push({ source, code: 'wrong_types', params: { names: result.wrongType.map((w) => w.name).join(', ') } });
    }
  } else {
    for (const w of result.wrongType) {
      issues.push({ source, code: `wrong_type_as_${w.usedAs}`, params: { standard, name: w.name } });
    }
  }
  return issues;
}

// checkExampleStructure's problems ({ kind, ... }) as issues.
export function structureIssues(problems, { schema } = {}) {
  return (problems || []).map(({ kind, ...params }) => ({ source: 'example', code: kind, params: { ...params, schema } }));
}

// invalidRuleXPaths' expressions as issues.
export function xpathIssues(expressions) {
  return (expressions || []).map((expression) => ({ source: 'rule', code: 'invalid_xpath', params: { expression } }));
}

// The issue in the interface language (`t` from i18next). An unknown code
// shows as the code itself, never as nothing (HR7).
export function formatSchemaIssue(issue, t) {
  const key = SCHEMA_ISSUE_KEYS[issue.source]?.[issue.code];
  if (!key) return issue.code;
  const params = { ...issue.params };
  if (Array.isArray(params.suggestions)) params.suggestions = joinList(params.suggestions, t('records.assistant.listOr'));
  if (Array.isArray(params.standards)) params.standards = formatStandardList(params.standards, t('records.assistant.listAnd'));
  return t(key, params);
}

// A stable React key for an issue.
export function schemaIssueKey(issue) {
  return `${issue.source}:${issue.code}:${JSON.stringify(issue.params)}`;
}
