"""Docs request ("Servicio de fichas de esquema y su uso en Ask") -- loads
the per-standard schema "cards" generated by
`backend/scripts/generate_schema_cards.py` (backend/schema_cards/*.json,
NOT public/ -- these are backend-only, never fetched whole by the frontend;
`GET /api/schema-cards` serves them compactly instead) and answers lookups
for `app.api.routes.schema_cards`.

Same standard->file mapping as `src/utils/vocabularyCheck.js`'s
STANDARD_TO_VOCABULARY_FILE (both DITA Xpath flavors share one file; S1000D
5.0/6.0 have no schema in this repo, so no cards file for them either --
"standard sin fichas -> respuesta explícita de 'no disponible'", never a
false empty result).
"""
import json
import re
from pathlib import Path

STANDARD_TO_SCHEMA_CARDS_FILE = {
    "DITA 1.3 Xpath2.0": "schema-cards-dita.json",
    "DITA 1.3 Xpath3.0": "schema-cards-dita.json",
    "S1000D 3.0.1": "schema-cards-3-0-1.json",
    "S1000D 4.1": "schema-cards-4-1.json",
    "S1000D 4.2": "schema-cards-4-2.json",
}

_CARDS_DIR = Path(__file__).resolve().parents[2] / "schema_cards"

# Compact-output limits (docs request point 2) -- must match the defaults
# documented in generate_schema_cards.py's own module docstring (kept as a
# separate constant, not a shared import, since that script is a one-off
# CLI tool never imported by the running app, same convention already
# established for generate_schema_vocabulary.py).
MAX_CHILDREN = 40
MAX_ATTRIBUTES = 30
MAX_ENUM_VALUES = 20

# "Did you mean con marcado a medias y listas de padres cortadas" round,
# Part 2: `parents` (the inverse index -- "what elements allow THIS one as
# a child") was cut at the same MAX_CHILDREN=40 as an element's own direct
# children, but the two lists have nothing to do with each other and don't
# need the same limit -- <para> in S1000D 4.2 genuinely has 43 real
# parents (every element `<para>` may appear inside), just over the old
# 40 cutoff, so a real "Where can <para> go?" answer always hit the
# "+3 more" case even though 43 is still a short, readable list on its
# own. Counted directly against the real generated cards
# (backend/schema_cards/*.json) before picking 60, for elements whose
# parents list exceeds 40 vs 60:
#
#   S1000D 3.0.1: 4 elements over 40  (refs=127, applic=119, dscr=86, fldname=86)  -- same 4 still over 60
#   S1000D 4.1:   7 elements over 40  (refs=149, description=118, descr=91, fieldName=87, title=80, dmRef=43, name=43) -- 5 still over 60
#   S1000D 4.2:   8 elements over 40  (refs=152, description=118, descr=91, title=88, fieldName=87, dmRef=47, name=43, para=43) -- 5 still over 60 (para drops out: 43 <= 60)
#   DITA 1.3:     137 elements over 40 -- 60 elements still over 60 (DITA's inverse index is far denser -- common inline elements like `data`/`text`/`keyword` are legitimately allowed inside hundreds of container elements; 60 does not make this list exhaustive for DITA, only less aggressively cut than 40 was)
#
# 60 clears <para>'s real 43 (the encargo's own worked example) while
# still bounding the genuinely huge DITA/`refs`-style cases -- raising it
# further would keep chasing DITA's long tail without ever reaching
# "never truncated" for it, so MAX_PARENTS stays a real cap, not a promise
# that every element's parent list is always shown whole; see Part 2's own
# "(partial list: N of M shown)" wording in buildSchemaFactsBlock for how a
# genuinely truncated list is now marked, never silently.
MAX_PARENTS = 60


def _load_all_cards() -> dict[str, dict]:
    """Loads every schema-cards-*.json referenced by the standard map into
    memory ONCE, at import time (docs request: "las fichas se cargan en
    memoria del backend al arrancar") -- this module is imported exactly
    once, by app.api.routes.schema_cards, itself imported once by
    app.main at process startup. A standard whose file doesn't exist on
    disk (S1000D 5.0/6.0 -- no schema in this repo) is simply absent from
    the result; `get_schema_cards` below turns that into the documented
    "not available" response, never a crash or a silent empty result."""
    loaded: dict[str, dict] = {}
    for filename in sorted(set(STANDARD_TO_SCHEMA_CARDS_FILE.values())):
        path = _CARDS_DIR / filename
        if path.exists():
            loaded[filename] = json.loads(path.read_text(encoding="utf-8"))
    return loaded


_CARDS_BY_FILE = _load_all_cards()

# Suggest Rule part 2 (schema context): the schema variants a rule can be
# limited to. Every schema file that appears in a card, minus the four
# imported helper schemas that are never a document type of their own:
# dc/rdf/xlink (Dublin Core, RDF, XLink namespaces) and xcf (the WebCGM
# companion-file schema -- its elements are webcgm/grobject/linkuri/
# bindById/bindByName, confirmed against sources/SchemasS1000D/4.2/xcf.xsd).
_NON_DOCUMENT_SCHEMAS = frozenset({"dc", "rdf", "xlink", "xcf"})


def _document_schemas(data: dict) -> list[str]:
    found: set[str] = set()
    for variants in data.get("cards", {}).values():
        for variant in variants:
            found.update(variant.get("schemas", []))
    return sorted(found - _NON_DOCUMENT_SCHEMAS)


_DOCUMENT_SCHEMAS_BY_FILE = {filename: _document_schemas(data) for filename, data in _CARDS_BY_FILE.items()}


# DITA (T4): the merged DITA cards have a single schema ("DITA 1.3"); for
# the Test rule panel its document types are the topic types, in the order
# the client prefers them for a general rule (app.services.
# rule_test_skeletons builds one graph and skeleton per type).
DITA_DOCUMENT_TYPES = ("topic", "concept", "task", "reference", "troubleshooting", "map")


def get_document_schemas(standard: str) -> list[str]:
    """Sorted document-type schema names of `standard` ([] when it has no
    cards); for DITA, its topic types in preference order."""
    filename = STANDARD_TO_SCHEMA_CARDS_FILE.get(standard)
    if filename == "schema-cards-dita.json":
        return list(DITA_DOCUMENT_TYPES)
    return list(_DOCUMENT_SCHEMAS_BY_FILE.get(filename, [])) if filename else []

# "Pulido de fichas" round, point 1: real data (schema-cards-4-2.json,
# <para>'s @caveat/@securityClassification) has enums like cv01..cv99 or
# 01..99 -- 99 near-identical tokens that used to get cut at MAX_ENUM_VALUES
# (20) with a "+79 more" note, hiding the fact the list is actually a clean,
# gap-free numeric sequence. A value must be `<prefix><digits>` with the
# SAME prefix and the SAME zero-padded digit width across every value in
# the enum (mixed widths/prefixes, or anything non-numeric like
# changeType's add/delete/modify, bail out to `None` -- caller falls back
# to the normal list + truncation).
_ENUM_TOKEN_RE = re.compile(r"^([A-Za-z_]*)(\d+)$")


def _collapse_enum_to_ranges(values: list[str]) -> list[str] | None:
    """Collapses a consecutive-numeric enum into range tokens (`cv01–cv99`,
    or several with gaps: `cv01–cv20, cv51–cv99`) -- always representing
    the COMPLETE list losslessly (a lone value stays a single token, never
    gains a dash). Returns None if the values don't form one clean
    sequence (mixed prefix/width, non-numeric values, anything the regex
    doesn't match) -- the caller then falls back to the pre-existing
    truncate-at-MAX_ENUM_VALUES behavior, unchanged."""
    if not values:
        return None
    parsed = []
    prefixes: set[str] = set()
    widths: set[int] = set()
    for v in values:
        m = _ENUM_TOKEN_RE.match(v)
        if not m:
            return None
        prefix, digits = m.groups()
        parsed.append(int(digits))
        prefixes.add(prefix)
        widths.add(len(digits))
    if len(prefixes) != 1 or len(widths) != 1:
        return None
    prefix = next(iter(prefixes))
    width = next(iter(widths))

    def fmt(n: int) -> str:
        return f"{prefix}{str(n).zfill(width)}"

    numbers = sorted(set(parsed))
    tokens: list[str] = []
    start = prev = numbers[0]
    for n in numbers[1:]:
        if n == prev + 1:
            prev = n
            continue
        tokens.append(fmt(start) if start == prev else f"{fmt(start)}–{fmt(prev)}")
        start = prev = n
    tokens.append(fmt(start) if start == prev else f"{fmt(start)}–{fmt(prev)}")
    return tokens


def _collapse_or_cut_enum(enum: list[str], cut: bool) -> tuple[list[str], bool, int]:
    """(values, truncated, omitted) for one enum: a long one collapses into
    ranges when it is a clean sequence (lossless); otherwise it is cut to
    MAX_ENUM_VALUES only when `cut` (full cards keep every value)."""
    if len(enum) <= MAX_ENUM_VALUES:
        return enum, False, 0
    collapsed = _collapse_enum_to_ranges(enum)
    if collapsed is not None:
        return collapsed, False, 0
    if not cut:
        return enum, False, 0
    return enum[:MAX_ENUM_VALUES], True, len(enum) - MAX_ENUM_VALUES


def _compact_variant(variant: dict, full: bool = False) -> dict:
    """One card variant for the endpoint. `full` (C1, Ask's deterministic
    answers): no list is cut -- a structural answer lists every child,
    attribute and value; long enums still collapse into ranges."""
    max_attributes = None if full else MAX_ATTRIBUTES
    max_children = None if full else MAX_CHILDREN
    attributes = variant.get("attributes", [])
    attributes_truncated = max_attributes is not None and len(attributes) > max_attributes
    compact_attributes = []
    for attr in attributes[:max_attributes]:
        enum = attr.get("enum")
        enum_truncated = False
        enum_omitted = 0
        if enum:
            # "Ajustes al juego de pruebas de prompts" round, Part 4: only
            # collapse into a range when the enum actually NEEDS it -- a
            # short, already-readable enum (cat: 1-2, allowedObjectFlag:
            # 0-2, asp: 1-3) reads better as a plain list. Collapsing runs
            # on the FULL enum, before any cut, so a range always represents
            # the complete list.
            enum, enum_truncated, enum_omitted = _collapse_or_cut_enum(enum, cut=not full)
        compact_attributes.append(
            {
                "name": attr["name"],
                "required": attr["required"],
                "enum": enum,
                "enum_truncated": enum_truncated,
                "enum_omitted": enum_omitted,
            }
        )

    children = variant.get("children", [])
    children_truncated = max_children is not None and len(children) > max_children
    children_omitted = len(children) - max_children if children_truncated else 0

    return {
        "schemas": variant.get("schemas", []),
        "attributes": compact_attributes,
        "attributes_truncated": attributes_truncated,
        "attributes_omitted": len(attributes) - max_attributes if attributes_truncated else 0,
        "children": children[:max_children],
        "children_truncated": children_truncated,
        "children_omitted": children_omitted,
        "resolved": variant.get("resolved", True),
    }


def get_schema_cards(
    standard: str, names: list[str], full: bool = False
) -> tuple[bool, dict[str, list[dict]], list[str]]:
    """Returns (available, cards, unknown) for the requested element
    names against `standard`'s cards file. `available=False` (cards={},
    unknown=every requested name) means this standard has no generated
    schema cards at all -- distinct from a name simply not existing in a
    standard that DOES have cards (that name lands in `unknown` with
    `available=True`). `full`: no list is cut (see _compact_variant)."""
    filename = STANDARD_TO_SCHEMA_CARDS_FILE.get(standard)
    data = _CARDS_BY_FILE.get(filename) if filename else None
    if data is None:
        return False, {}, sorted(dict.fromkeys(names))

    all_cards = data.get("cards", {})
    all_parents = data.get("parents", {})
    cards: dict[str, dict] = {}
    unknown: list[str] = []
    seen: set[str] = set()
    for name in names:
        if name in seen:
            continue
        seen.add(name)
        variants = all_cards.get(name)
        if variants is None:
            unknown.append(name)
            continue
        parents = all_parents.get(name, [])
        max_parents = None if full else MAX_PARENTS
        parents_truncated = max_parents is not None and len(parents) > max_parents
        cards[name] = {
            "variants": [_compact_variant(v, full=full) for v in variants],
            "parents": parents[:max_parents],
            "parents_truncated": parents_truncated,
            "parents_omitted": len(parents) - max_parents if parents_truncated else 0,
        }
    return True, cards, sorted(unknown)


def get_attribute_owners(standard: str, name: str) -> tuple[bool, list[dict]]:
    """(available, owners): every element that declares attribute `name`,
    one entry per card variant -- {element, schemas, required, enum} with
    the enum complete (long ones collapsed into ranges). C1: what Ask's
    deterministic "which values does @x take" answer reads. Sorted by
    element name."""
    filename = STANDARD_TO_SCHEMA_CARDS_FILE.get(standard)
    data = _CARDS_BY_FILE.get(filename) if filename else None
    if data is None:
        return False, []
    owners: list[dict] = []
    for element, variants in sorted(data.get("cards", {}).items()):
        for variant in variants:
            for attr in variant.get("attributes", []):
                if attr["name"] != name:
                    continue
                enum = attr.get("enum")
                owners.append(
                    {
                        "element": element,
                        "schemas": variant.get("schemas", []),
                        "required": attr["required"],
                        "enum": _collapse_or_cut_enum(enum, cut=False)[0] if enum else None,
                    }
                )
    return True, owners
