"""Docs request ("Servicio de fichas de esquema y su uso en Ask") -- loads
the per-standard schema "cards" generated by
`backend/scripts/generate_schema_cards.py` (backend/schema_cards/*.json,
NOT public/ -- these are backend-only, never fetched whole by the frontend;
`GET /api/schema-cards` serves them compactly instead) and answers lookups
for `app.api.routes.schema_cards`.

Same standard->file mapping as `src/utils/vocabularyCheck.js`'s
STANDARD_TO_VOCABULARY_FILE (both DITA Xpath flavors share one file; S1000D
5.0/6.0 have no schema in this repo, so no cards file for them either --
"standard sin fichas -> respuesta explícita de 'no disponible'", never a
false empty result).
"""
import json
import re
from pathlib import Path

STANDARD_TO_SCHEMA_CARDS_FILE = {
    "DITA 1.3 Xpath2.0": "schema-cards-dita.json",
    "DITA 1.3 Xpath3.0": "schema-cards-dita.json",
    "S1000D 3.0.1": "schema-cards-3-0-1.json",
    "S1000D 4.1": "schema-cards-4-1.json",
    "S1000D 4.2": "schema-cards-4-2.json",
}

_CARDS_DIR = Path(__file__).resolve().parents[2] / "schema_cards"

# Compact-output limits (docs request point 2) -- must match the defaults
# documented in generate_schema_cards.py's own module docstring (kept as a
# separate constant, not a shared import, since that script is a one-off
# CLI tool never imported by the running app, same convention already
# established for generate_schema_vocabulary.py).
MAX_CHILDREN = 40
MAX_ATTRIBUTES = 30
MAX_ENUM_VALUES = 20


def _load_all_cards() -> dict[str, dict]:
    """Loads every schema-cards-*.json referenced by the standard map into
    memory ONCE, at import time (docs request: "las fichas se cargan en
    memoria del backend al arrancar") -- this module is imported exactly
    once, by app.api.routes.schema_cards, itself imported once by
    app.main at process startup. A standard whose file doesn't exist on
    disk (S1000D 5.0/6.0 -- no schema in this repo) is simply absent from
    the result; `get_schema_cards` below turns that into the documented
    "not available" response, never a crash or a silent empty result."""
    loaded: dict[str, dict] = {}
    for filename in sorted(set(STANDARD_TO_SCHEMA_CARDS_FILE.values())):
        path = _CARDS_DIR / filename
        if path.exists():
            loaded[filename] = json.loads(path.read_text(encoding="utf-8"))
    return loaded


_CARDS_BY_FILE = _load_all_cards()

# "Pulido de fichas" round, point 1: real data (schema-cards-4-2.json,
# <para>'s @caveat/@securityClassification) has enums like cv01..cv99 or
# 01..99 -- 99 near-identical tokens that used to get cut at MAX_ENUM_VALUES
# (20) with a "+79 more" note, hiding the fact the list is actually a clean,
# gap-free numeric sequence. A value must be `<prefix><digits>` with the
# SAME prefix and the SAME zero-padded digit width across every value in
# the enum (mixed widths/prefixes, or anything non-numeric like
# changeType's add/delete/modify, bail out to `None` -- caller falls back
# to the normal list + truncation).
_ENUM_TOKEN_RE = re.compile(r"^([A-Za-z_]*)(\d+)$")


def _collapse_enum_to_ranges(values: list[str]) -> list[str] | None:
    """Collapses a consecutive-numeric enum into range tokens (`cv01–cv99`,
    or several with gaps: `cv01–cv20, cv51–cv99`) -- always representing
    the COMPLETE list losslessly (a lone value stays a single token, never
    gains a dash). Returns None if the values don't form one clean
    sequence (mixed prefix/width, non-numeric values, anything the regex
    doesn't match) -- the caller then falls back to the pre-existing
    truncate-at-MAX_ENUM_VALUES behavior, unchanged."""
    if not values:
        return None
    parsed = []
    prefixes: set[str] = set()
    widths: set[int] = set()
    for v in values:
        m = _ENUM_TOKEN_RE.match(v)
        if not m:
            return None
        prefix, digits = m.groups()
        parsed.append(int(digits))
        prefixes.add(prefix)
        widths.add(len(digits))
    if len(prefixes) != 1 or len(widths) != 1:
        return None
    prefix = next(iter(prefixes))
    width = next(iter(widths))

    def fmt(n: int) -> str:
        return f"{prefix}{str(n).zfill(width)}"

    numbers = sorted(set(parsed))
    tokens: list[str] = []
    start = prev = numbers[0]
    for n in numbers[1:]:
        if n == prev + 1:
            prev = n
            continue
        tokens.append(fmt(start) if start == prev else f"{fmt(start)}–{fmt(prev)}")
        start = prev = n
    tokens.append(fmt(start) if start == prev else f"{fmt(start)}–{fmt(prev)}")
    return tokens


def _compact_variant(variant: dict) -> dict:
    attributes = variant.get("attributes", [])
    attributes_truncated = len(attributes) > MAX_ATTRIBUTES
    compact_attributes = []
    for attr in attributes[:MAX_ATTRIBUTES]:
        enum = attr.get("enum")
        enum_truncated = False
        enum_omitted = 0
        if enum:
            # "Ajustes al juego de pruebas de prompts" round, Part 4: only
            # collapse into a range when the enum actually NEEDS it -- a
            # short, already-readable enum (cat: 1-2, allowedObjectFlag:
            # 0-2, asp: 1-3) reads better as a plain list than as a range
            # token, and was never the problem this mechanism was built for
            # (that was cv01..cv99/01..99, 99 near-identical values getting
            # cut to "20 + 79 more"). Collapsing still runs on the FULL,
            # untruncated enum -- BEFORE the MAX_ENUM_VALUES slice below --
            # so a long range genuinely represents the complete list, never
            # a truncated slice of it (unchanged from the previous round);
            # it's just gated on actually being long enough to need it.
            if len(enum) > MAX_ENUM_VALUES:
                collapsed = _collapse_enum_to_ranges(enum)
                if collapsed is not None:
                    enum = collapsed
                else:
                    enum_truncated = True
                    enum_omitted = len(enum) - MAX_ENUM_VALUES
                    enum = enum[:MAX_ENUM_VALUES]
        compact_attributes.append(
            {
                "name": attr["name"],
                "required": attr["required"],
                "enum": enum,
                "enum_truncated": enum_truncated,
                "enum_omitted": enum_omitted,
            }
        )

    children = variant.get("children", [])
    children_truncated = len(children) > MAX_CHILDREN
    children_omitted = max(0, len(children) - MAX_CHILDREN) if children_truncated else 0

    return {
        "schemas": variant.get("schemas", []),
        "attributes": compact_attributes,
        "attributes_truncated": attributes_truncated,
        "attributes_omitted": max(0, len(attributes) - MAX_ATTRIBUTES) if attributes_truncated else 0,
        "children": children[:MAX_CHILDREN],
        "children_truncated": children_truncated,
        "children_omitted": children_omitted,
        "resolved": variant.get("resolved", True),
    }


def get_schema_cards(standard: str, names: list[str]) -> tuple[bool, dict[str, list[dict]], list[str]]:
    """Returns (available, cards, unknown) for the requested element
    names against `standard`'s cards file. `available=False` (cards={},
    unknown=every requested name) means this standard has no generated
    schema cards at all -- distinct from a name simply not existing in a
    standard that DOES have cards (that name lands in `unknown` with
    `available=True`)."""
    filename = STANDARD_TO_SCHEMA_CARDS_FILE.get(standard)
    data = _CARDS_BY_FILE.get(filename) if filename else None
    if data is None:
        return False, {}, sorted(dict.fromkeys(names))

    all_cards = data.get("cards", {})
    all_parents = data.get("parents", {})
    cards: dict[str, dict] = {}
    unknown: list[str] = []
    seen: set[str] = set()
    for name in names:
        if name in seen:
            continue
        seen.add(name)
        variants = all_cards.get(name)
        if variants is None:
            unknown.append(name)
            continue
        parents = all_parents.get(name, [])
        parents_truncated = len(parents) > MAX_CHILDREN
        cards[name] = {
            "variants": [_compact_variant(v) for v in variants],
            "parents": parents[:MAX_CHILDREN],
            "parents_truncated": parents_truncated,
            "parents_omitted": max(0, len(parents) - MAX_CHILDREN) if parents_truncated else 0,
        }
    return True, cards, sorted(unknown)
