// Docs request (Suggest Proposal round, "comprobación de vocabulario contra
// el esquema"): checks element/attribute names mentioned in a BRDP's
// Title/Definition/Proposal against the REAL schema vocabulary of the
// project's standard, generated by backend/scripts/generate_schema_
// vocabulary.py from the actual XSDs (never guessed, never LLM-judged --
// see checkAgainstVocabulary below).
//
// Real-Mistral follow-up round ("solo determinista, sin bloqueo, sin
// referencias inventadas"): the LLM-guess extraction path was removed
// entirely -- only the deterministic path below remains, which requires
// actual evidence in the text (`<x>`/`@x` markup, or a name explicitly
// introduced via "element .../attribute ...") before ever calling a name
// a candidate at all.
//
// Follow-up round ("consejo de nombres sin falsos positivos"): a real
// report against this app -- "Atributos seleccionados para la etiqueta
// <stranger>" -> "Did you mean `@seleccionados`?"; "Decidir qué atributos
// usar en el elemento <stranger> y cómo usarlos." -> "Did you mean
// `@usar`?" and "Did you mean `<c>`?" -- exposed two real bugs, both fixed
// below, never with an LLM:
//   (a) a phrase-triggered bare word ("seleccionados", "usar") was
//       reported as a vocabulary WARNING (notFound) purely because it sat
//       right after "atributo(s)"/"elemento(s)", even though in Spanish
//       (and English) that word is very often an adjective or verb, not a
//       name -- e.g. "atributos SELECCIONADOS", "atributos a USAR". Fixed
//       by no longer letting a phrase-triggered candidate contribute to
//       notFound/wrongType AT ALL -- it is used ONLY to offer a "Did you
//       mean" suggestion, and only when the word actually resolves
//       against the real vocabulary (see resolvePhraseCandidates below).
//       A word that isn't in the vocabulary either way is silently
//       ignored -- no warning, no suggestion (accepted limitation: "el
//       elemento pokemon" -- a genuinely invented name -- gets nothing).
//   (b) the tokenizer only matched ASCII letters ([A-Za-z]), so an
//       accented word like "cómo" split into fragments ("c" + "mo") at
//       the accented character -- and because the list-continuation
//       feature (a previous round) treats "y"/"and"/etc. as continuing a
//       trigger's candidate list, the single-letter fragment "c" (from
//       "...elemento <stranger> y cómo...") got chained onto the
//       "elemento" trigger's list as if it were a second candidate,
//       producing the nonsensical "Did you mean `<c>`?". Fixed with a
//       Unicode-aware tokenizer (`\p{L}` letters, digits, and the XML
//       name characters -, _, .) so accented/composed words are always
//       captured whole -- never fragmented -- combined with (a) above
//       (even a whole, correctly-tokenized "cómo" would still resolve to
//       nothing and be ignored, since it isn't in any real schema).
export const STANDARD_TO_VOCABULARY_FILE = {
  'DITA 1.3 Xpath2.0': 'schema-vocabulary-dita.json',
  'DITA 1.3 Xpath3.0': 'schema-vocabulary-dita.json',
  'S1000D 3.0.1': 'schema-vocabulary-3-0-1.json',
  'S1000D 4.1': 'schema-vocabulary-4-1.json',
  'S1000D 4.2': 'schema-vocabulary-4-2.json',
};

const _vocabularyCache = new Map();

// Returns { elements: Set<string>, attributes: Set<string> } for a standard
// with a generated vocabulary, or null if the standard has none (HR7 --
// the caller must show "not available", never silently skip or, worse,
// silently claim every name is fine).
export async function loadSchemaVocabulary(standard) {
  const file = STANDARD_TO_VOCABULARY_FILE[standard];
  if (!file) return null;
  if (_vocabularyCache.has(file)) return _vocabularyCache.get(file);
  const res = await fetch(`/${file}?v=` + Date.now());
  if (!res.ok) throw new Error(`Could not load ${file}`);
  const json = await res.json();
  const parsed = { elements: new Set(json.elements || []), attributes: new Set(json.attributes || []) };
  _vocabularyCache.set(file, parsed);
  return parsed;
}

// Deterministic context extraction -- the ONLY extraction path.
// - `elements`: whatever appears between `<...>` (opening or closing tag
//   form), e.g. `<pokemon>`/`</pokemon>` -> "pokemon".
// - `attributes`: whatever appears after `@`, e.g. `@conref` -> "conref".
// - `camelCase`: lower-camelCase words (e.g. "proceduralStep") -- checked
//   against the UNION of elements+attributes by checkAgainstVocabulary,
//   exactly like explicit markup, with its own "Not found" warning.
// - `phraseCandidates`: words introduced via "elemento(s)/element(s)/
//   atributo(s)/attribute(s)/etiqueta(s)/tag(s)" (see extractPhraseCandidates)
//   -- NEVER checked for notFound/wrongType (follow-up round: too often an
//   adjective or verb, not a name). Only used by resolvePhraseCandidates
//   to build a "Did you mean" suggestion, and only for names that
//   genuinely exist in the real vocabulary. Excludes any name already
//   properly marked up elsewhere in the same text (already present in
//   `elements`/`attributes`).
export function extractContextCandidates(text) {
  const source = text || '';
  const elements = new Set();
  const attributes = new Set();

  let match;
  ELEMENT_ATTR_TAG_RE.lastIndex = 0;
  while ((match = ELEMENT_ATTR_TAG_RE.exec(source))) elements.add(match[1]);

  ATTR_MARKER_RE.lastIndex = 0;
  while ((match = ATTR_MARKER_RE.exec(source))) attributes.add(match[1]);

  // "Did you mean con marcado a medias" round, Part 1: a half-typed tag
  // ("Title above the <table", "above the table>") is just as explicit an
  // intent to mark up an element as a complete `<table>` -- the missing
  // bracket is a typo, not ambiguity about whether the author meant to
  // mark it up at all. So these names are folded into the SAME `elements`
  // Set that checkAgainstVocabulary reads -- UNLIKE phraseCandidates below
  // (which never produce a warning, only a suggestion): a dangling name
  // that doesn't exist in the schema gets the same red "not found" banner
  // a complete `<pokemon>` would, per the encargo ("porque la intención de
  // marcar es explícita"). A name already captured via a complete tag
  // elsewhere in the same text is never duplicated. `danglingElements`
  // (returned separately below) is ONLY the subset of names that were
  // genuinely incomplete -- used later to also offer a "Did you mean
  // <name>?" completion when the name resolves (resolveDanglingElement
  // Suggestions), the same way a phrase-triggered word does.
  const danglingElements = [];
  for (const name of extractDanglingElementNames(source)) {
    if (elements.has(name)) continue;
    elements.add(name);
    danglingElements.push(name);
  }

  const camelCase = extractCamelCaseCandidates(source);

  const rawPhraseCandidates = extractPhraseCandidates(source);
  const phraseCandidates = [];
  const seenPhrase = new Set();
  for (const c of rawPhraseCandidates) {
    if (elements.has(c.name) || attributes.has(c.name)) continue; // already marked up somewhere in this text
    const key = `${c.type}:${c.name}`;
    if (seenPhrase.has(key)) continue;
    seenPhrase.add(key);
    phraseCandidates.push({ name: c.name, type: c.type });
  }

  return { elements: [...elements], attributes: [...attributes], camelCase, phraseCandidates, danglingElements };
}

// Finds names introduced via HALF-typed bracket markup, with no trigger
// word required: "<name" with nothing (or a non-">"-character) right
// after the name, or "name>" with nothing (or a non-"<"/word-char) right
// before it. Deliberately does NOT use a single "greedy name then
// lookahead" regex -- `<([\p{L}][\w-]*)(?!>)` would backtrack the
// quantifier down to a shorter match whenever the FULL name IS followed
// by ">" (i.e. exactly the complete-tag case that must be excluded),
// silently capturing a truncated name instead of correctly matching
// nothing. Matching the name greedily first and then checking the single
// character immediately after/before it in plain JS avoids that
// backtracking trap entirely.
// Never a false positive on a plain comparison/arrow ("a < b", "x<5",
// "->"): the character right after "<" (open case) or right before ">"
// (close case) must be a LETTER, immediately adjacent to the bracket --
// "a < b" has a space there, "x<5" has a digit, "->" has no "<" at all.
function extractDanglingElementNames(text) {
  const source = text || '';
  const names = new Set();

  OPEN_TOKEN_RE.lastIndex = 0;
  let m;
  while ((m = OPEN_TOKEN_RE.exec(source))) {
    const endIdx = m.index + m[0].length;
    if (source[endIdx] !== '>') names.add(m[1]);
  }

  CLOSE_TOKEN_RE.lastIndex = 0;
  while ((m = CLOSE_TOKEN_RE.exec(source))) {
    const before = m.index > 0 ? source[m.index - 1] : undefined;
    if (before !== undefined && (before === '<' || NAME_CHAR_RE.test(before))) continue;
    names.add(m[1]);
  }

  return [...names];
}

// Follow-up round ("sin falsos positivos"): the ONLY place a phrase-
// triggered candidate can turn into anything user-visible -- a "Did you
// mean" suggestion, NEVER a warning. A candidate resolves only if it
// genuinely exists in the vocabulary, as EITHER kind:
//   - exists as the kind the trigger implied ("atributo table" where
//     `table` is a real attribute) -> suggested as that kind;
//   - exists only as the OTHER kind ("atributo table" where `table` is
//     really an element) -> suggested with the CORRECTED kind
//     (`<table>`, never `@table`);
//   - exists as neither -> dropped entirely, no suggestion, no warning
//     (accepted limitation: a genuinely invented name like "pokemon"
//     never gets a suggestion).
// `vocabulary` may be null (standard with no generated vocabulary) -- in
// that case nothing can be resolved, so this returns [] rather than
// guessing.
export function resolvePhraseCandidates(phraseCandidates, vocabulary) {
  if (!vocabulary) return [];
  const seen = new Set();
  const resolved = [];
  for (const c of phraseCandidates) {
    if (seen.has(c.name)) continue;
    const vocabSet = c.type === 'element' ? vocabulary.elements : vocabulary.attributes;
    const otherSet = c.type === 'element' ? vocabulary.attributes : vocabulary.elements;
    let type;
    if (vocabSet.has(c.name)) type = c.type;
    else if (otherSet.has(c.name)) type = c.type === 'element' ? 'attribute' : 'element';
    else continue; // doesn't exist as either kind -- ignored entirely
    seen.add(c.name);
    resolved.push({ name: c.name, type });
  }
  return resolved;
}

// "Did you mean con marcado a medias" round, Part 1: half-typed markup
// (`danglingElements` from extractContextCandidates) only ever suggests
// COMPLETING the bracket as an element -- unlike resolvePhraseCandidates
// above, it never flips to `@name`. The author already chose "<"/">" as
// the delimiter; the fix is to close it, never to change what kind of
// markup it is. A name that doesn't exist as an element in the vocabulary
// is never suggested here -- it already gets its own red "not found" (or
// wrongType, if it exists only as an attribute) warning from
// checkAgainstVocabulary, since extractContextCandidates folds these
// names into the same `elements` Set that check reads.
export function resolveDanglingElementSuggestions(danglingElementNames, vocabulary) {
  if (!vocabulary) return [];
  const seen = new Set();
  const resolved = [];
  for (const name of danglingElementNames) {
    if (seen.has(name)) continue;
    if (!vocabulary.elements.has(name)) continue;
    seen.add(name);
    resolved.push({ name, type: 'element' });
  }
  return resolved;
}

// Rewrites `text` to wrap the first bare (not already `<...>`/`@...`-marked)
// occurrence of `suggestion.name` with the markup its `type` implies --
// the "Did you mean `<pokemon>`?" fix-it action. Word-boundary match, case
// as written by the user (never re-cased). A no-op (returns `text`
// unchanged) if the name can no longer be found bare -- the caller re-runs
// extractContextCandidates after applying anyway, so a suggestion that's
// gone stale simply stops appearing rather than throwing.
//
// Ask-with-schema-cards follow-up round: a real report against this app --
// title "Element <table" (an unclosed "<" immediately before the name) --
// showed the button doing NOTHING. Root cause: the previous single regex
// `(?<![<@\w])name(?!\w)` treats ANY "<" right before the name as "already
// marked up" and refuses to match there at all -- for "Element <table"
// "table" only occurs once, immediately after that dangling "<", so the
// whole regex found zero matches anywhere and returned the input
// unchanged. The mirrored case ("table>", a dangling trailing ">" with no
// opening "<") used to match as a bare word and get wrapped AGAIN,
// producing a doubled bracket ("<table>>"). Both are now handled as their
// own cases, tried in order from most to least specific, so incomplete
// markup is completed (never doubled) and a genuinely bare word is wrapped
// normally:
//   1. `<name>` (already fully, correctly marked up) -- nothing to fix.
//   2. `<name` with no closing `>` right after -- add ONLY the missing
//      closing bracket, keep the existing opening one.
//   3. `name>` with no opening `<` right before -- add ONLY the missing
//      opening bracket, keep the existing closing one.
//   4. a genuinely bare occurrence -- wrap with both brackets.
// Attributes have no closing delimiter (`@name` is complete the moment the
// `@` is there), so they only ever need the bare-word case; a name already
// following `@` was already excluded upstream (extractContextCandidates
// never offers it as a phrase candidate to begin with).
export function applyRenameSuggestion(text, suggestion) {
  const source = text || '';
  const escaped = suggestion.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const bareRe = new RegExp(`(?<![<@\\w])${escaped}(?!\\w)`, 'u');

  if (suggestion.type === 'attribute') {
    const m = bareRe.exec(source);
    if (!m) return source;
    return source.slice(0, m.index) + `@${suggestion.name}` + source.slice(m.index + suggestion.name.length);
  }

  if (new RegExp(`<${escaped}>`, 'u').test(source)) return source; // already correct

  const danglingOpenRe = new RegExp(`<${escaped}(?!\\w)`, 'u'); // "<table", no ">" right after
  let m = danglingOpenRe.exec(source);
  if (m) return source.slice(0, m.index) + `<${suggestion.name}>` + source.slice(m.index + m[0].length);

  const danglingCloseRe = new RegExp(`(?<![<\\w])${escaped}>`, 'u'); // "table>", no "<" right before
  m = danglingCloseRe.exec(source);
  if (m) return source.slice(0, m.index) + `<${suggestion.name}>` + source.slice(m.index + m[0].length);

  m = bareRe.exec(source);
  if (!m) return source;
  return source.slice(0, m.index) + `<${suggestion.name}>` + source.slice(m.index + suggestion.name.length);
}

const ELEMENT_ATTR_TAG_RE = /<\/?([A-Za-z][\w-]*)[^>]*>/g;
const ATTR_MARKER_RE = /@([A-Za-z][\w-]*)/g;
// "Did you mean con marcado a medias" round, Part 1: used only by
// extractDanglingElementNames above. `<` must be immediately (no space)
// followed by a letter -- this is what excludes "a < b"/"x<5" as
// candidates, not any check against the vocabulary.
const OPEN_TOKEN_RE = /<([\p{L}][\p{L}\p{N}_-]*)/gu;
const CLOSE_TOKEN_RE = /([\p{L}][\p{L}\p{N}_-]*)>/gu;
const NAME_CHAR_RE = /[\p{L}\p{N}_-]/u;
// Unicode-aware word tokenizer (follow-up round, point 3): letters in any
// script (`\p{L}`), digits, and the XML name characters -, _, . -- so an
// accented/composed word like "cómo"/"señal"/"utilizará" is always
// captured as ONE token, never fragmented at the accented character (the
// old ASCII-only [A-Za-z][\w-]* pattern broke "cómo" into "c" + "mo",
// which the list-continuation feature below could then chain onto a
// trigger's candidate list as a spurious single-letter "name").
const WORD_RE = /[\p{L}][\p{L}\p{N}_.-]*|,/gu;
const CAMEL_CASE_TOKEN_RE = /[\p{L}][\p{L}\p{N}_.-]*/gu;
// Follow-up round, point 2: requires at least two lowercase letters before
// the first uppercase one, AND a minimum total length of 5 -- "lA" (1
// lowercase, then uppercase) no longer matches; "dmCode"/"dmRef"/
// "proceduralStep"/"applicRefId" still do. The camelCase pattern itself
// stays ASCII (a-z/A-Z) -- real camelCase identifiers in this app's
// schemas are always ASCII; the Unicode-aware tokenizer above only
// matters for not FRAGMENTING a word before this pattern is tested
// against it.
const CAMEL_CASE_RE = /^[a-z]{2,}[A-Z][A-Za-z0-9]*$/;
const CAMEL_CASE_MIN_LENGTH = 5;

// Follow-up round, point 4: "etiqueta(s)"/"tag(s)" are real synonyms for
// "elemento(s)"/"element(s)" that a real user actually typed ("la
// etiqueta <stranger>") -- added as element-type triggers, same
// mechanism as the existing ones (the type-detection below only special-
// cases the attribute-type spellings, so these fall through to 'element'
// automatically, same as "elemento"/"element" already did).
const TRIGGER_WORDS = new Set([
  'elemento', 'elementos', 'element', 'elements',
  'etiqueta', 'etiquetas', 'tag', 'tags',
  'atributo', 'atributos', 'attribute', 'attributes',
]);
// Words skipped between a trigger word and the real candidate -- the
// original connectors (articles/prepositions) PLUS, per the follow-up
// round, the descriptive words a real report showed leaking through as
// false-positive candidates ("atributo de tipo cl" must yield "cl", never
// "tipo").
const SKIP_WORDS = new Set([
  'el', 'la', 'los', 'las', 'del', 'de', 'un', 'una', 'unos', 'unas', 'the', 'of', 'a', 'an',
  'tipo', 'type', 'llamado', 'llamada', 'named', 'called', 'nombre', 'name',
]);
// Words that continue a list right after a just-captured candidate ("cl,
// pl ni ip" / "cl, pl and ip") -- only interpreted as continuators
// immediately after a candidate, never elsewhere in the sentence.
const LIST_CONTINUATION_WORDS = new Set(['y', 'o', 'ni', 'and', 'or']);

function tokenize(text) {
  const out = [];
  let m;
  WORD_RE.lastIndex = 0;
  while ((m = WORD_RE.exec(text))) {
    out.push(m[0] === ',' ? { type: 'comma' } : { type: 'word', value: m[0] });
  }
  return out;
}

// Skips over SKIP_WORDS starting at `idx`; stops (without consuming) at a
// trigger word, a comma, or anything else.
function skipSkipWords(tokens, idx) {
  let i = idx;
  while (i < tokens.length && tokens[i].type === 'word' && SKIP_WORDS.has(tokens[i].value.toLowerCase())) i++;
  return i;
}

// Phrase-trigger extraction with list capture: the word following
// "elemento(s)/element(s)/atributo(s)/attribute(s)/etiqueta(s)/tag(s)",
// skipping SKIP_WORDS between the trigger and the real candidate -- if a
// SECOND trigger word is hit while skipping, the scan re-anchors on that
// later trigger instead (e.g. "atributos del elemento pokemon" captures
// "pokemon", tied to "elemento"). Once the first candidate is found, the
// scan continues capturing a comma/conjunction-separated list ("cl, pl ni
// ip"), skipping SKIP_WORDS again between each list separator and its
// word, and stops at the first word that isn't a clean list continuation.
// Each returned candidate carries `type` ('element' | 'attribute') from
// the trigger word that started its list. These candidates are ONLY ever
// resolved into a suggestion (never a warning) -- see
// resolvePhraseCandidates above.
function extractPhraseCandidates(text) {
  const tokens = tokenize(text);
  const candidates = [];
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];
    if (t.type !== 'word' || !TRIGGER_WORDS.has(t.value.toLowerCase())) continue;
    const lower = t.value.toLowerCase();
    const type = lower.startsWith('atributo') || lower.startsWith('attribute') ? 'attribute' : 'element';

    let j = skipSkipWords(tokens, i + 1);
    if (j >= tokens.length || tokens[j].type !== 'word') continue;
    if (TRIGGER_WORDS.has(tokens[j].value.toLowerCase())) continue; // re-anchor: let the outer loop reach this trigger itself

    candidates.push({ name: tokens[j].value, type });
    let k = j + 1;
    // List continuation: comma or a list conjunction, then (skipping
    // SKIP_WORDS again) another word -- repeat until the pattern breaks.
    while (true) {
      let k2 = k;
      let isContinuator = false;
      if (tokens[k2] && tokens[k2].type === 'comma') {
        k2++;
        isContinuator = true;
      } else if (tokens[k2] && tokens[k2].type === 'word' && LIST_CONTINUATION_WORDS.has(tokens[k2].value.toLowerCase())) {
        k2++;
        isContinuator = true;
      }
      if (!isContinuator) break;
      k2 = skipSkipWords(tokens, k2);
      if (k2 >= tokens.length || tokens[k2].type !== 'word' || TRIGGER_WORDS.has(tokens[k2].value.toLowerCase())) break;
      candidates.push({ name: tokens[k2].value, type });
      k = k2 + 1;
    }
    i = k - 1; // avoid rescanning consumed list words as fresh triggers
  }
  return candidates;
}

function extractCamelCaseCandidates(text) {
  const tokens = text.match(CAMEL_CASE_TOKEN_RE) || [];
  return tokens.filter((t) => t.length >= CAMEL_CASE_MIN_LENGTH && CAMEL_CASE_RE.test(t));
}

// The only step that decides existence, purely deterministically against
// the real vocabulary. `vocabulary` is what loadSchemaVocabulary() returns,
// or null if not available for this standard.
//
// Returns { available, notFound, wrongType }:
// - `notFound`: display strings (`<x>`/`@x`/bare) for names found via
//   explicit `<x>`/`@x` markup or camelCase -- the only two sources that
//   feed this (follow-up round: phrase-triggered bare words NEVER
//   contribute here any more, see extractContextCandidates/
//   resolvePhraseCandidates above).
// - `wrongType`: `{ name, usedAs, actualAs }` for a name used as one kind
//   (element/attribute) that doesn't exist as that kind but DOES exist as
//   the other -- reported instead of (never in addition to) notFound for
//   that name. Only applies to explicit markup (camelCase's kind is
//   genuinely unknown, so it is never wrong-kind-checked).
export function checkAgainstVocabulary(contextCandidates, vocabulary) {
  if (!vocabulary) return { available: false, notFound: [], wrongType: [] };

  const notFound = new Map();
  const wrongType = new Map();

  const considerTyped = (name, type) => {
    const vocabSet = type === 'element' ? vocabulary.elements : vocabulary.attributes;
    const otherSet = type === 'element' ? vocabulary.attributes : vocabulary.elements;
    if (vocabSet.has(name)) return; // known as the kind it was used as -- fine
    if (otherSet.has(name)) {
      if (!wrongType.has(name)) {
        wrongType.set(name, { name, usedAs: type, actualAs: type === 'element' ? 'attribute' : 'element' });
      }
      return;
    }
    const display = type === 'element' ? `<${name}>` : `@${name}`;
    if (!notFound.has(name)) notFound.set(name, display);
  };

  const considerCamelCase = (name) => {
    if (vocabulary.elements.has(name) || vocabulary.attributes.has(name)) return;
    if (!notFound.has(name)) notFound.set(name, name);
  };

  for (const name of contextCandidates.elements) considerTyped(name, 'element');
  for (const name of contextCandidates.attributes) considerTyped(name, 'attribute');
  for (const name of contextCandidates.camelCase) considerCamelCase(name);

  // A wrong-kind finding is its own, more specific message -- never also
  // listed as merely "not found" for the same name.
  for (const name of wrongType.keys()) notFound.delete(name);

  return {
    available: true,
    notFound: [...notFound.values()].sort(),
    wrongType: [...wrongType.values()].sort((a, b) => a.name.localeCompare(b.name)),
  };
}

// Formats one wrongType entry into the exact sentence shape the encargo
// asks for. Exported so the UI and buildUnknownNamesBlock format it
// identically (never two independently-drifting copies).
export function formatWrongTypeMessage(standard, entry) {
  const usedDisplay = entry.usedAs === 'element' ? `<${entry.name}>` : `@${entry.name}`;
  const actualDisplay = entry.actualAs === 'element' ? `element <${entry.name}>` : `attribute @${entry.name}`;
  // Both "element" and "attribute" start with a vowel sound -- "an" either way.
  return `${usedDisplay} is not an ${entry.usedAs} in ${standard} — it exists as ${actualDisplay}.`;
}

// Docs request ("Servicio de fichas de esquema y su uso en Ask"): which
// names to request a schema CARD for, from a given text -- reusing the
// EXACT same deterministic extraction the vocabulary-warning banner
// already uses (explicit `<x>`/`@x` markup, camelCase, and phrase-triggered
// words), restricted to names that actually EXIST in the vocabulary (an
// inexistent name already has its own red warning; it never gets a schema
// card, there is nothing real to fetch). This is also, by construction,
// how the encargo's own "no cards for bare words that coincidentally match
// a schema name" requirement is satisfied: extractContextCandidates never
// treats an untriggered, unmarked bare word (e.g. "para", "note" used as
// ordinary Spanish/English words) as a candidate AT ALL -- there is no
// "scan every word against the vocabulary" step to begin with, so nothing
// extra is needed here.
//
// ELEMENT names only: the generator ("una ficha por elemento", docs
// request point 1) never produces a card for a bare attribute -- an
// attribute's own facts (required/enum) only exist as part of whichever
// element card declares it. A `@frame` mentioned on its own therefore
// never gets its own fetch; its information already surfaces inside the
// `<table>` card wherever `<table>` itself is a selected name.
export function extractSchemaFactCandidates(text, vocabulary) {
  if (!vocabulary) return [];
  const { elements, camelCase, phraseCandidates } = extractContextCandidates(text);
  const results = [];
  const seen = new Set();
  const add = (name) => {
    if (seen.has(name)) return;
    seen.add(name);
    results.push({ name, type: 'element' });
  };
  for (const name of elements) if (vocabulary.elements.has(name)) add(name);
  for (const name of camelCase) if (vocabulary.elements.has(name)) add(name);
  for (const r of resolvePhraseCandidates(phraseCandidates, vocabulary)) {
    if (r.type === 'element') add(r.name);
  }
  return results;
}

// Selects up to `max` names across several texts, in PRIORITY ORDER (the
// encargo's own wording: "priorizando los de la pregunta y luego los del
// Title" -- Definition/Proposal are extracted too, per the encargo's
// "aplicada... a Title/Definition/Proposal", but at lower priority still,
// after Title, since only those two are named explicitly as the priority
// pair). Dedupes across texts (a name mentioned in both the question and
// the Title only ever asks for one card, keeping its higher priority).
export function selectSchemaFactNames(orderedTexts, vocabulary, max = 6) {
  if (!vocabulary) return [];
  const seen = new Set();
  const selected = [];
  for (const text of orderedTexts) {
    if (selected.length >= max) break;
    for (const candidate of extractSchemaFactCandidates(text, vocabulary)) {
      if (selected.length >= max) break;
      if (seen.has(candidate.name)) continue;
      seen.add(candidate.name);
      selected.push(candidate);
    }
  }
  return selected;
}

// Ask-with-schema-cards follow-up round, point 4 ("fichas más compactas con
// variantes"): a real report against this app -- `<para>` in S1000D 4.2
// has 8 variants, and the previous rendering repeated every attribute and
// child for EACH of the 8, producing a wall of near-identical text that
// buried the one or two things that actually differ between variants.
// `entry` is the exact shape GET /api/schema-cards returns for one name
// ({variants: [{schemas, attributes, children, resolved, ...}], parents,
// ...}) -- this function never re-fetches or reformats that data, only
// re-partitions it into "common to every variant" vs "per-variant diff",
// so buildSchemaFactsBlock (the prompt) and SchemaFactCard (the UI) can
// share one single, testable computation instead of two independently-
// drifting formatters.
//
// `parents` is already NOT per-variant in this data (one list for the
// whole element, see backend/app/services/schema_cards.py) -- so it is
// already "common" by construction and is returned as-is, never diffed.
//
// Attributes: an attribute counts as common only if EVERY variant has one
// with the exact same name AND required-ness AND enum (including its own
// truncation flags) -- a same-named attribute that differs in any of
// those between variants is genuinely a difference, so it is left OUT of
// the common set and shown per-variant instead, never silently merged.
// Children: common iff the name appears in every variant's children list
// (plain set membership, no attached properties to compare).
//
// A single-variant entry (the overwhelmingly common case) returns
// `common: null` -- there is nothing to summarize across variants, so
// callers should render it the old, simple way (this function only ever
// changes the OUTPUT SHAPE for entries that genuinely have more than one
// variant, per the encargo's own "si un elemento tiene varias variantes").
function attributeSignature(attr) {
  return [attr.name, attr.required, JSON.stringify(attr.enum || null), !!attr.enum_truncated, attr.enum_omitted || 0].join('\u0000');
}

export function summarizeSchemaFactEntry(entry) {
  const variants = entry.variants || [];
  if (variants.length <= 1) return { common: null, variants, anyUnresolved: variants.some((v) => !v.resolved) };

  const attrSigSets = variants.map((v) => new Set((v.attributes || []).map(attributeSignature)));
  const commonAttrSigs = [...attrSigSets[0]].filter((sig) => attrSigSets.every((s) => s.has(sig)));
  const commonAttrSigSet = new Set(commonAttrSigs);
  const commonAttributes = (variants[0].attributes || []).filter((a) => commonAttrSigSet.has(attributeSignature(a)));

  const childSets = variants.map((v) => new Set(v.children || []));
  const commonChildren = [...childSets[0]].filter((name) => childSets.every((s) => s.has(name)));
  const commonChildSet = new Set(commonChildren);

  const perVariant = variants.map((v) => ({
    schemas: v.schemas,
    resolved: v.resolved,
    diffAttributes: (v.attributes || []).filter((a) => !commonAttrSigSet.has(attributeSignature(a))),
    attributes_truncated: v.attributes_truncated,
    attributes_omitted: v.attributes_omitted,
    diffChildren: (v.children || []).filter((name) => !commonChildSet.has(name)),
    children_truncated: v.children_truncated,
    children_omitted: v.children_omitted,
  }));

  return {
    common: { attributes: commonAttributes, children: commonChildren },
    perVariant,
    anyUnresolved: variants.some((v) => !v.resolved),
  };
}

// A cheap, stable, non-cryptographic hash of the three text fields --
// only used as an in-memory key to avoid recomputing when nothing changed,
// never for anything security-sensitive.
export function hashVocabInputText(title, definition, proposal) {
  const s = `${title || ''}\u0000${definition || ''}\u0000${proposal || ''}`;
  let hash = 0;
  for (let i = 0; i < s.length; i++) {
    hash = (Math.imul(hash, 31) + s.charCodeAt(i)) | 0;
  }
  return hash.toString(36);
}
