// Docs request (Suggest Proposal round, "comprobación de vocabulario contra
// el esquema"): checks element/attribute names mentioned in a BRDP's
// Title/Definition/Proposal against the REAL schema vocabulary of the
// project's standard, generated by backend/scripts/generate_schema_
// vocabulary.py from the actual XSDs (never guessed, never LLM-judged --
// see checkAgainstVocabulary below).
//
// Two independent extraction paths, unioned (3.3 of the docs request):
//   (a) extractContextCandidates() -- deterministic, no LLM call.
//   (b) extractVocabCandidatesViaLLM() -- a SEPARATE, prior LLM call
//       (temperature 0) that only extracts what the text is TALKING
//       ABOUT as an element/attribute name -- it is never told the real
//       vocabulary and never judges whether a name is valid. That
//       decision is made by checkAgainstVocabulary() alone, deterministically.
import { sendMessage } from '../api/llmAPI.js';

// Only DITA has a full schema available in this repo (sources/D1.3/schema)
// -- see backend/scripts/generate_schema_vocabulary.py and CLAUDE.md's
// closeout note on SchemasS1000D (not present in this sandbox at all, so
// no S1000D standard has a generated vocabulary file yet). Both DITA
// flavors share the same schema (the XPath dialect only affects Rule
// authoring, never the topic/element vocabulary), so both map to the
// same file. Adding a real S1000D vocabulary later is just: run the
// generator against a real, complete SchemasS1000D issue folder, add the
// resulting public/schema-vocabulary-<issue>.json here -- no other code
// change needed.
const STANDARD_TO_VOCABULARY_FILE = {
  'DITA 1.3 Xpath2.0': 'schema-vocabulary-dita.json',
  'DITA 1.3 Xpath3.0': 'schema-vocabulary-dita.json',
};

const _vocabularyCache = new Map();

// Returns { elements: Set<string>, attributes: Set<string> } for a standard
// with a generated vocabulary, or null if the standard has none (HR7 --
// the caller must show "not available", never silently skip or, worse,
// silently claim every name is fine).
export async function loadSchemaVocabulary(standard) {
  const file = STANDARD_TO_VOCABULARY_FILE[standard];
  if (!file) return null;
  if (_vocabularyCache.has(file)) return _vocabularyCache.get(file);
  const res = await fetch(`/${file}?v=` + Date.now());
  if (!res.ok) throw new Error(`Could not load ${file}`);
  const json = await res.json();
  const parsed = { elements: new Set(json.elements || []), attributes: new Set(json.attributes || []) };
  _vocabularyCache.set(file, parsed);
  return parsed;
}

// 3.3(a) -- deterministic context extraction, no LLM involved.
// - `elements`: whatever appears between `<...>` (opening or closing tag
//   form), e.g. `<pokemon>`/`</pokemon>` -> "pokemon".
// - `attributes`: whatever appears after `@`, e.g. `@conref` -> "conref".
// - `ambiguous`: two further heuristics whose category (element vs
//   attribute) the surrounding natural-language text doesn't pin down
//   with confidence, so (per 3.4) they get checked against the UNION of
//   both lists rather than guessing which one:
//     - the word following "elemento(s)/element(s)/atributo(s)/
//       attribute(s)", skipping over articles/connectors
//       (el/la/los/las/del/de/un/una/unos/unas/the/of/a/an) that sit
//       between the trigger word and the real candidate -- if a SECOND
//       trigger word is hit while skipping connectors (e.g. "atributos
//       del elemento pokemon"), the scan re-anchors on that later
//       trigger instead, so the word actually captured is the one right
//       after the trigger that's closest to it.
//     - lower-camelCase words (e.g. "proceduralStep").
const ELEMENT_ATTR_TAG_RE = /<\/?([A-Za-z][\w-]*)[^>]*>/g;
const ATTR_MARKER_RE = /@([A-Za-z][\w-]*)/g;
const WORD_RE = /[A-Za-z][\w-]*/g;
const CAMEL_CASE_RE = /^[a-z][a-z0-9]*[A-Z][A-Za-z0-9]*$/;

const TRIGGER_WORDS = new Set(['elemento', 'elementos', 'element', 'elements', 'atributo', 'atributos', 'attribute', 'attributes']);
const CONNECTOR_WORDS = new Set(['el', 'la', 'los', 'las', 'del', 'de', 'un', 'una', 'unos', 'unas', 'the', 'of', 'a', 'an']);

function extractPhraseCandidates(text) {
  const tokens = text.match(WORD_RE) || [];
  const candidates = [];
  for (let i = 0; i < tokens.length; i++) {
    if (!TRIGGER_WORDS.has(tokens[i].toLowerCase())) continue;
    let j = i + 1;
    while (j < tokens.length && CONNECTOR_WORDS.has(tokens[j].toLowerCase())) j++;
    if (j >= tokens.length) continue;
    if (TRIGGER_WORDS.has(tokens[j].toLowerCase())) continue; // re-anchor: let the outer loop reach this trigger itself
    candidates.push(tokens[j]);
  }
  return candidates;
}

function extractCamelCaseCandidates(text) {
  const tokens = text.match(WORD_RE) || [];
  return tokens.filter((t) => CAMEL_CASE_RE.test(t));
}

export function extractContextCandidates(text) {
  const source = text || '';
  const elements = new Set();
  const attributes = new Set();
  const ambiguous = new Set();

  let match;
  ELEMENT_ATTR_TAG_RE.lastIndex = 0;
  while ((match = ELEMENT_ATTR_TAG_RE.exec(source))) elements.add(match[1]);

  ATTR_MARKER_RE.lastIndex = 0;
  while ((match = ATTR_MARKER_RE.exec(source))) attributes.add(match[1]);

  for (const w of extractPhraseCandidates(source)) ambiguous.add(w);
  for (const w of extractCamelCaseCandidates(source)) ambiguous.add(w);

  return { elements: [...elements], attributes: [...attributes], ambiguous: [...ambiguous] };
}

// 3.3(b) -- the extraction call's own system prompt. Deliberately never
// mentions or includes the real vocabulary -- existence is never this
// call's job (checkAgainstVocabulary decides that, deterministically).
export function buildVocabExtractionPrompt() {
  return `You extract candidate XML element and attribute names from a short
piece of business-rule text (a BRDP's Title/Definition/Proposal).

Read the text and list every word the text uses AS the name of an XML
element or attribute -- regardless of whether such an element or
attribute actually exists in any real schema. Do NOT judge whether a
name is real, valid, or well-known; that is decided elsewhere, by a
different process, not by you. You are only extracting what the text is
talking about as an element/attribute name.

Return ONLY a JSON object, nothing else -- no markdown, no code fences,
no explanation -- in exactly this shape:
{"elements": ["name1", "name2"], "attributes": ["name3"]}

If there are none of one kind, return an empty array for it. If there
are none at all, return {"elements": [], "attributes": []}.`;
}

// Tolerant JSON parse: strips a markdown code fence if the model added one
// anyway, and validates the shape. Returns null (never throws) on
// anything that doesn't parse into the expected shape.
export function parseVocabExtractionResponse(raw) {
  if (typeof raw !== 'string') return null;
  let text = raw.trim();
  const fenceMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenceMatch) text = fenceMatch[1].trim();
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return null;
  const elements = Array.isArray(parsed.elements) ? parsed.elements.filter((x) => typeof x === 'string') : null;
  const attributes = Array.isArray(parsed.attributes) ? parsed.attributes.filter((x) => typeof x === 'string') : null;
  if (elements === null || attributes === null) return null;
  return { elements, attributes };
}

// Runs the extraction call for real. Never throws -- a failed call or an
// invalid response degrades to `unavailable: true` (HR7: the caller must
// show "Extended name check unavailable" explicitly, per 3.3, rather than
// silently proceeding as if nothing was extracted).
export async function extractVocabCandidatesViaLLM({ title, definition, proposal, aiProvider }) {
  if (!aiProvider) return { elements: [], attributes: [], unavailable: true };
  const userMessage = `Title: ${title || ''}\nDefinition: ${definition || ''}\nProposal: ${proposal || ''}`;
  try {
    const res = await sendMessage(
      [{ role: 'user', content: userMessage }],
      null,
      aiProvider.model,
      aiProvider.provider,
      buildVocabExtractionPrompt(),
      { temperature: 0 }
    );
    const parsed = parseVocabExtractionResponse(res.content);
    if (!parsed) return { elements: [], attributes: [], unavailable: true };
    return { elements: parsed.elements, attributes: parsed.attributes, unavailable: false };
  } catch {
    return { elements: [], attributes: [], unavailable: true };
  }
}

// 3.4 -- the only step that decides existence, purely deterministically
// against the real vocabulary (never the LLM). `vocabulary` is what
// loadSchemaVocabulary() returns, or null if not available for this
// standard. `candidates` is the UNION of (a) and (b)'s output, already
// merged by the caller (mergeCandidates below).
//
// Display form is picked by where the name came from: `<name>` for an
// element-context match, `@name` for an attribute-context match, bare
// for an ambiguous one -- and deduped by the underlying name (not
// display form), since the same name can surface from more than one
// path (e.g. "<pokemon>" also tokenizes into the ambiguous camelCase/
// phrase scan) -- the more specific `<x>`/`@x` form wins over a bare one.
export function checkAgainstVocabulary(candidates, vocabulary) {
  if (!vocabulary) return { available: false, unknownNames: [] };
  const unknown = new Map();
  for (const name of candidates.elements) {
    if (!vocabulary.elements.has(name) && !unknown.has(name)) unknown.set(name, `<${name}>`);
  }
  for (const name of candidates.attributes) {
    if (!vocabulary.attributes.has(name) && !unknown.has(name)) unknown.set(name, `@${name}`);
  }
  for (const name of candidates.ambiguous) {
    if (vocabulary.elements.has(name) || vocabulary.attributes.has(name)) continue;
    if (!unknown.has(name)) unknown.set(name, name);
  }
  return { available: true, unknownNames: [...unknown.values()].sort() };
}

// Unions (a)'s and (b)'s candidate sets into the single shape
// checkAgainstVocabulary expects -- (b)'s own elements/attributes are
// folded in as their own typed buckets (the LLM WAS asked to classify
// them), not dumped into `ambiguous`.
export function mergeCandidates(contextCandidates, llmCandidates) {
  return {
    elements: [...new Set([...contextCandidates.elements, ...(llmCandidates?.elements || [])])],
    attributes: [...new Set([...contextCandidates.attributes, ...(llmCandidates?.attributes || [])])],
    ambiguous: contextCandidates.ambiguous,
  };
}

// A cheap, stable, non-cryptographic hash of the three text fields --
// only used as an in-memory cache key ("mismo texto dos veces -> una
// sola llamada de extracción"), never for anything security-sensitive.
export function hashVocabInputText(title, definition, proposal) {
  const s = `${title || ''}\u0000${definition || ''}\u0000${proposal || ''}`;
  let hash = 0;
  for (let i = 0; i < s.length; i++) {
    hash = (Math.imul(hash, 31) + s.charCodeAt(i)) | 0;
  }
  return hash.toString(36);
}
